#!/usr/bin/env node
// tests/conformance.mjs — cross-language config-parser conformance.
//
// THE permanent fence against parser drift (audit H2/H3/H8/H10/M14): ctx.py,
// ctx.mjs and ctx.sh must read the SAME config the SAME way, or fail the SAME
// way. Every fixture runs through all three parsers:
//   ctx.py  — the real Ctx() in a throwaway git repo (python3, full tree as
//             JSON + the `python3 ctx.py <key>` CLI for scalar keys)
//   ctx.mjs — parseConfig imported directly (the same function config.mjs and
//             every .mjs gate use)
//   ctx.sh  — vteam_cfg, scalar keys only (its documented subset); flow
//             mappings must be REFUSED loudly, never misread or defaulted
// Error fixtures (tabs, malformed flow) must fail in BOTH py and mjs, nonzero,
// with the same message shape. Any divergence exits nonzero.
//
// Standalone:  node tests/conformance.mjs
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import process from "node:process";
import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import { parseConfig } from "../core/scripts/lib/ctx.mjs";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const LIB = path.join(ROOT, "core", "scripts", "lib");
const CTX_PY = path.join(LIB, "ctx.py");
const CTX_SH = path.join(LIB, "ctx.sh");

// ---- fixture sources read from the repo (drift in THEM must break THIS) ----
function readmeConfig() {
  const readme = fs.readFileSync(path.join(ROOT, "README.md"), "utf8");
  const m = readme.match(/```yaml\n(# vteam\.config\.yaml — generated by init[^]*?)```/);
  if (!m) {
    console.error("conformance: could not find the documented config block in README.md " +
      "(fence starting '# vteam.config.yaml — generated by init') — update this extractor " +
      "WITH the README, the docs' config must stay parseable");
    process.exit(1);
  }
  return m[1];
}
const exampleConfig = fs.readFileSync(
  path.join(ROOT, "core", "templates", "vteam.config.example.yaml"), "utf8");

// ---- fixtures ---------------------------------------------------------------
// expect:  dotted key -> expected value (checked in py AND mjs trees; string/
//          number values are ALSO checked through the `python3 ctx.py <key>` CLI)
// sh:      dotted key -> exact expected vteam_cfg stdout (scalar subset only)
// shFail:  keys vteam_cfg must REFUSE (exit 1 + stderr, empty stdout)
// error:   regex both py and mjs must die with (nonzero / throw)
const FIXTURES = [
  {
    name: "block style",
    config: "version: 1\nproject:\n  name: My App\n  key: PROJ\npaths:\n  pm: docs/pm\n  evidence: evd\n",
    expect: { "version": 1, "project.name": "My App", "project.key": "PROJ", "paths.pm": "docs/pm" },
    sh: { "version": "1", "project.key": "PROJ", "paths.pm": "docs/pm" },
  },
  {
    name: "flow maps w/ nested lists (H2+H3)",
    config: "stack: { profile: node, package_manager: npm }\n" +
      "docs:\n  task_context:\n" +
      "    always: [docs/architecture.md]\n" +
      "    by_label: { payment: [docs/specs/billing.md, docs/specs/refunds.md], auth: [docs/auth.md] }\n",
    expect: {
      "stack.profile": "node",
      "stack.package_manager": "npm",
      "docs.task_context.always": ["docs/architecture.md"],
      "docs.task_context.by_label.payment": ["docs/specs/billing.md", "docs/specs/refunds.md"],
      "docs.task_context.by_label.auth": ["docs/auth.md"],
    },
    shFail: ["stack.profile"], // flow section: refuse loudly, never default
  },
  {
    name: "inline lists",
    config: "git:\n  code_paths: [src/, prisma/]\ntracker:\n  done_statuses: [Done, Closed, Resolved]\nreview:\n  high_stakes_paths: []\n",
    expect: {
      "git.code_paths": ["src/", "prisma/"],
      "tracker.done_statuses": ["Done", "Closed", "Resolved"],
      "review.high_stakes_paths": [],
    },
    sh: { "git.code_paths": "[src/, prisma/]" }, // documented: raw bracket text
  },
  {
    name: "dash lists",
    config: "autonomy:\n  level: assisted\n  exemptions:\n    - real-money\n    - legal\n",
    expect: { "autonomy.level": "assisted", "autonomy.exemptions": ["real-money", "legal"] },
    sh: { "autonomy.level": "assisted" },
  },
  {
    name: "quoted values w/ colons",
    config: "project:\n  name: 'My App: The \"Sequel\"'\ngit:\n  branch_pattern: \"^(feat|fix)/{key}-[0-9]+-\"\n",
    expect: {
      "project.name": 'My App: The "Sequel"',
      "git.branch_pattern": "^(feat|fix)/{key}-[0-9]+-",
    },
    sh: {
      "project.name": 'My App: The "Sequel"',
      "git.branch_pattern": "^(feat|fix)/{key}-[0-9]+-",
    },
  },
  {
    name: "trailing comments",
    config: "project:\n  key: TST            # ticket prefix\npaths:\n  pm: docs/pm         # decisions.md, log.md, sessions/\nstack: { profile: node }   # flow with a comment\n",
    expect: { "project.key": "TST", "paths.pm": "docs/pm", "stack.profile": "node" },
    sh: { "project.key": "TST", "paths.pm": "docs/pm" },
    shFail: ["stack.profile"],
  },
  {
    name: "3-level nesting",
    config: "a:\n  b:\n    c: deep\n    d:\n      - x\n  e: 2\n",
    expect: { "a.b.c": "deep", "a.b.d": ["x"], "a.e": 2 },
    sh: { "a.e": "2" },
  },
  {
    name: "empty values",
    config: "project:\n  name: ''\n  key: PROJ\n  motto: keep\tcalm\ndocs:\n  by_label: {}\nspecs:\n  sources: []\nempty_section:\n",
    expect: {
      "project.name": "",
      "project.motto": "keep\tcalm", // tab INSIDE a value stays legal
      "docs.by_label": {},
      "specs.sources": [],
      "empty_section": {},
    },
    sh: { "project.name": "", "project.motto": "keep\tcalm" }, // M14: empty ≠ absent
    shAbsent: ["no.such.key"], // absent without default: exit 1, print nothing
  },
  {
    name: "scalar where list expected",
    config: "tracker:\n  done_statuses: Done\ngit:\n  code_paths: src/\n",
    expect: { "tracker.done_statuses": "Done", "git.code_paths": "src/" },
    sh: { "tracker.done_statuses": "Done", "git.code_paths": "src/" },
  },
  {
    name: "README documented config (verbatim)",
    config: readmeConfig(),
    expect: {
      "project.name": "My Project",
      "project.key": "PROJ",
      "stack.profile": "node",
      "stack.package_manager": "npm",
      "paths.evidence": "evd",
      "git.protected_branch": "main",
      "git.branch_pattern": "^(feat|fix)/{key}-[0-9]+-",
      "git.merge_strategy": "merge",
      "tracker.provider": "markdown",
      "autonomy.level": "assisted",
      "autonomy.self_merge": false,
      "review.reviewers": 2,
      "review.high_stakes_paths": ["prisma/schema.prisma"],
      "review.high_stakes_terms": ["wallet", "refund", "payout"],
      "docs.task_context.always": ["docs/architecture.md"],
      "docs.task_context.by_label.payment": ["docs/specs/billing.md"],
    },
    sh: { "git.protected_branch": "main", "git.merge_strategy": "merge", "git.hooks": "managed" },
    shFail: ["project.key", "paths.evidence", "stack.profile", "tracker.provider"], // flow sections
  },
  {
    name: "shipped vteam.config.example.yaml",
    config: exampleConfig,
    expect: {
      "version": 1,
      "project.key": "PROJ",
      "project.adopted": "2026-01-01",
      "paths.pm": "docs/pm",
      "paths.evidence": "evd",
      "specs.sources": [],
      "docs.task_context.always": [],
      "docs.task_context.by_label": {},
      "stack.profile": "generic",
      "git.branch_pattern": "^(feat|fix)/{key}-[0-9]+-",
      "git.code_paths": ["src/"],
      "tracker.done_statuses": ["Done", "Closed", "Resolved"],
      "tracker.review_status": "In Review",
      "team.capacity_per_day": 0.8,
      "autonomy.self_merge": false,
      "autonomy.exemptions": ["real-money", "legal", "purchasing", "credentials", "data-deletion"],
      "review.reviewers": 2,
      "models.routing": "default",
    },
    sh: {
      "project.key": "PROJ",
      "paths.pm": "docs/pm",         // the trailing comment that fooled migrate's old regex (H8)
      "paths.evidence": "evd",
      "tracker.review_status": "In Review",
      "stack.profile": "generic",
    },
  },
  {
    name: "tab indentation (must die)",
    config: "a:\n\tb: 1\n",
    error: /tab indentation is not supported — use spaces/,
  },
  {
    name: "malformed flow: entry without value (must die)",
    config: "stack: { profile }\n",
    error: /bad flow mapping entry/,
  },
  {
    name: "malformed flow: unterminated mapping (must die)",
    config: "stack: { profile: node\n",
    error: /unterminated flow mapping/,
  },
  {
    name: "malformed flow: unterminated list (must die)",
    config: "x: [a, b\n",
    error: /unterminated inline list/,
  },
];

// ---- runners ----------------------------------------------------------------
function makeRepo(configText) {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), "vteam-conformance-"));
  const g = spawnSync("git", ["init", "-q", dir], { encoding: "utf8" });
  if (g.status !== 0) { console.error("conformance: git init failed"); process.exit(1); }
  fs.writeFileSync(path.join(dir, "vteam.config.yaml"), configText);
  return dir;
}

/** Full tree through the real Ctx() (root resolution + config load + parse). */
function pyTree(repo) {
  const code = "import json, sys\n" +
    `sys.path.insert(0, ${JSON.stringify(LIB)})\n` +
    "from ctx import Ctx\n" +
    'print(json.dumps(Ctx()._cfg, separators=(",", ":")))\n';
  const r = spawnSync("python3", ["-c", code], { cwd: repo, encoding: "utf8",
    env: { ...process.env, PYTHONDONTWRITEBYTECODE: "1" } }); // never litter the package tree with __pycache__
  return { status: r.status, stdout: r.stdout, stderr: (r.stderr || "").trim() };
}

function pyCli(repo, key) {
  const r = spawnSync("python3", [CTX_PY, key], { cwd: repo, encoding: "utf8",
    env: { ...process.env, PYTHONDONTWRITEBYTECODE: "1" } });
  return { status: r.status, out: (r.stdout || "").replace(/\r?\n$/, "") };
}

function shCfg(repo, key) {
  const r = spawnSync("bash",
    ["-c", `. ${JSON.stringify(CTX_SH)} && vteam_cfg ${JSON.stringify(key)}`],
    { cwd: repo, encoding: "utf8" });
  return { status: r.status, out: (r.stdout || "").replace(/\r?\n$/, ""), err: (r.stderr || "").trim() };
}

function lookup(tree, dotted) {
  let node = tree;
  for (const part of dotted.split(".")) {
    if (node === null || typeof node !== "object" || Array.isArray(node) || !(part in node)) return undefined;
    node = node[part];
  }
  return node;
}
const J = JSON.stringify;

// ---- drive ------------------------------------------------------------------
let anyFail = false;
const rows = [];
for (const fx of FIXTURES) {
  const problems = [];
  const repo = makeRepo(fx.config);
  let py = "✅", mjs = "✅", sh = "✅", agree = "✅";
  try {
    if (fx.error) {
      // both parsers must FAIL, nonzero, with the same message shape
      const pr = pyTree(repo);
      if (pr.status === 0) { py = "❌"; problems.push(`py accepted a config it must reject`); }
      else if (!fx.error.test(pr.stderr)) { py = "❌"; problems.push(`py died with the wrong message: ${pr.stderr}`); }
      let mjsMsg = null;
      try { parseConfig(fx.config); } catch (e) { mjsMsg = e.message; }
      if (mjsMsg === null) { mjs = "❌"; problems.push(`mjs accepted a config it must reject`); }
      else if (!fx.error.test(mjsMsg)) { mjs = "❌"; problems.push(`mjs died with the wrong message: ${mjsMsg}`); }
      sh = "—";
      agree = (py === "✅" && mjs === "✅") ? "✅" : "❌";
    } else {
      // mjs tree
      let mjsTree = null;
      try { mjsTree = parseConfig(fx.config); }
      catch (e) { mjs = "❌"; problems.push(`mjs threw: ${e.message}`); }
      // py tree
      const pr = pyTree(repo);
      let pyT = null;
      if (pr.status !== 0) { py = "❌"; problems.push(`py failed: ${pr.stderr}`); }
      else { try { pyT = JSON.parse(pr.stdout); } catch { py = "❌"; problems.push(`py printed non-JSON: ${pr.stdout}`); } }
      // trees agree with each other
      if (pyT && mjsTree && J(pyT) !== J(mjsTree)) {
        agree = "❌";
        problems.push(`tree divergence:\n      py : ${J(pyT)}\n      mjs: ${J(mjsTree)}`);
      }
      // trees agree with EXPECTED
      for (const [key, want] of Object.entries(fx.expect ?? {})) {
        if (mjsTree && J(lookup(mjsTree, key)) !== J(want)) {
          mjs = "❌"; problems.push(`mjs ${key} = ${J(lookup(mjsTree, key))}, expected ${J(want)}`);
        }
        if (pyT && J(lookup(pyT, key)) !== J(want)) {
          py = "❌"; problems.push(`py ${key} = ${J(lookup(pyT, key))}, expected ${J(want)}`);
        }
        // scalar keys also through the real `python3 ctx.py <key>` CLI
        if (typeof want === "string" || typeof want === "number") {
          const c = pyCli(repo, key);
          if (c.status !== 0 || c.out !== String(want)) {
            py = "❌"; problems.push(`py CLI ${key} -> exit ${c.status} ${J(c.out)}, expected ${J(String(want))}`);
          }
        }
      }
      // ctx.sh — scalar subset
      for (const [key, want] of Object.entries(fx.sh ?? {})) {
        const r = shCfg(repo, key);
        if (r.status !== 0 || r.out !== want) {
          sh = "❌"; problems.push(`sh ${key} -> exit ${r.status} ${J(r.out)}, expected ${J(want)}`);
        }
      }
      for (const key of fx.shFail ?? []) {
        const r = shCfg(repo, key);
        if (r.status === 0 || r.out !== "" || !r.err) {
          sh = "❌"; problems.push(`sh ${key} must REFUSE (exit 1 + stderr, no stdout), got exit ${r.status} out=${J(r.out)} err=${J(r.err)}`);
        }
      }
      for (const key of fx.shAbsent ?? []) {
        const r = shCfg(repo, key);
        if (r.status === 0 || r.out !== "") {
          sh = "❌"; problems.push(`sh ${key} (absent, no default) must exit 1 and print nothing, got exit ${r.status} out=${J(r.out)}`);
        }
      }
      if (agree === "✅" && (py !== "✅" || mjs !== "✅" || sh !== "✅")) agree = "❌";
    }
  } finally {
    fs.rmSync(repo, { recursive: true, force: true });
  }
  if (problems.length) anyFail = true;
  rows.push({ name: fx.name, py, mjs, sh, agree, problems });
}

// ---- report -----------------------------------------------------------------
const W = Math.max(...rows.map((r) => r.name.length));
console.log(`${"fixture".padEnd(W)}  py  mjs  sh  agree`);
console.log("-".repeat(W + 22));
for (const r of rows) {
  console.log(`${r.name.padEnd(W)}  ${r.py}  ${r.mjs}   ${r.sh}  ${r.agree}`);
  for (const p of r.problems) console.log(`    ↳ ${p}`);
}
if (anyFail) {
  console.error("\nconformance: PARSERS DIVERGE — fix ctx.py/ctx.mjs/ctx.sh until all three agree.");
  process.exit(1);
}
console.log(`\nconformance: OK — ${rows.length} fixtures, ctx.py == ctx.mjs (== ctx.sh on its scalar subset), error fixtures red in both.`);
