#!/usr/bin/env python3
"""xlsx_export.py — turn a finished verification into a spreadsheet a manager
can open, filter and forward.

    python3 .vteam/scripts/xlsx_export.py --evd evd/SHOP-142
    python3 .vteam/scripts/xlsx_export.py --evd evd/SHOP-142 --out /tmp/SHOP-142.xlsx
    python3 .vteam/scripts/xlsx_export.py --selftest

The markdown pack is the record. This is the same record in the shape the rest
of the organisation already reads, laid out to the international test
documentation standard so nobody has to be taught how to read it:

    Summary       ISO/IEC/IEEE 29119-3 §8   test status report — the dashboard
    Test Cases    ISO/IEC/IEEE 29119-3 §7   test case specification (IEEE 829 fields)
    Defects       ISO/IEC/IEEE 29119-3 §9   incident report, graded by severity
    Traceability                            requirement -> case -> result -> defect
    Evidence                                every file, and what it shows

Three rules it does not break:

1. **It never invents a value.** A field the pack does not declare prints as
   NOT DECLARED, in muted grey, and is listed again in the summary's "declared
   unknowns" section. A severity guessed at because Major is the usual answer
   would make this file more dangerous than no file.
2. **It adds nothing.** Every cell is traceable to a line in the pack. There is
   no scoring, no weighting and no interpretation of its own.
3. **It says so when the pack contradicts itself** — a verdict that asserts a
   defect with no failed case, a PASS with one.

Exit 0 = written. Exit 1 = written, but `--strict` and the pack has declared
unknowns. Exit 2 = BLOCKED: nothing to export, or nowhere to write it.

Prove it:  python3 xlsx_export.py --selftest

Python 3.9 compatible. No third-party packages, by design.
"""
import argparse
import os
import re
import sys

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "lib"))

import evdpack  # noqa: E402
from evdpack import (SEVERITIES, SEVERITY_MEANING, ORIGINS, ORIGIN_MEANING, KINDS,  # noqa: E402
                     KIND_MEANING, CASE_RESULTS, RESULT_MEANING, NOT_DECLARED, VERDICTS,
                     VAGUE_VALUE)
import xlsx  # noqa: E402
from xlsx import S, N, B, Workbook, est_height  # noqa: E402

try:
    import ctx  # type: ignore
except Exception:  # pragma: no cover — the exporter must run without a config
    ctx = None

DASH = "—"

# ---------------------------------------------------------------------------
# labels
#
# The report itself is written in project.language, so the workbook follows the
# same setting. Column headers and section titles carry the English standard
# term alongside, so the same file serves a local stakeholder and an outside
# auditor without producing two files that can disagree.
# ---------------------------------------------------------------------------
_T = {
    "wb_title": ("Test case & defect report", "Báo cáo test case & lỗi"),
    "standard": ("Laid out to ISO/IEC/IEEE 29119-3 (test case specification, test status report "
                 "and incident report) with an IEEE-829-style field set and a requirement "
                 "traceability matrix. Severity follows this project's own ladder in "
                 "docs/qa/method/severity.md.",
                 "Trình bày theo ISO/IEC/IEEE 29119-3 (đặc tả test case, báo cáo tình trạng kiểm "
                 "thử và báo cáo lỗi), bộ trường theo kiểu IEEE 829, kèm ma trận truy vết yêu "
                 "cầu. Mức độ lỗi theo đúng thang của chính project này trong "
                 "docs/qa/method/severity.md."),
    "untitled": ("(the pack does not name this ticket)", "(gói bằng chứng không nêu tên ticket)"),
    # The one line that has to survive being printed, forwarded, or read on a
    # phone. Everything below it is the evidence for this sentence.
    "headline": ("{verdict}  ·  {cases} test case(s): {npass} passed, {nfail} failed, "
                 "{nblocked} blocked  ·  {ndefects} defect(s){sev}",
                 "{verdict}  ·  {cases} test case: {npass} đạt, {nfail} không đạt, "
                 "{nblocked} bị chặn  ·  {ndefects} lỗi{sev}"),
    "sev_none_graded": (" — none graded, so none can be prioritised",
                        " — chưa lỗi nào được đánh mức, nên chưa thể xếp ưu tiên"),
    "sev_worst": (", worst: {worst}", ", nặng nhất: {worst}"),
    "generated": ("Generated by ai-qa from {evd} · nothing here was typed by hand, and nothing "
                  "here was inferred: a blank in the pack prints as {nd}.",
                  "Sinh tự động bởi ai-qa từ {evd} · không có ô nào được nhập tay và không có ô "
                  "nào được suy diễn: thiếu trong gói bằng chứng thì in là {nd}."),

    "s1": ("1. What was tested, and against what", "1. Đã kiểm thử cái gì, đối chiếu với cái gì"),
    "s2": ("2. Test execution — how many cases, and how they ended",
           "2. Thực thi kiểm thử — bao nhiêu case, kết thúc thế nào"),
    "s3": ("3. Defects — how many, and how much they hurt",
           "3. Lỗi — bao nhiêu, và nghiêm trọng đến đâu"),
    "s4": ("4. The answer, in the verifier's own words",
           "4. Kết luận, theo đúng lời người kiểm thử"),
    "s5": ("5. Declared unknowns — what this pack does NOT say",
           "5. Điều chưa xác định — những gì gói bằng chứng KHÔNG nói"),
    "s6": ("6. How to read this workbook", "6. Cách đọc file này"),

    "ticket": ("Ticket", "Ticket"),
    "ticket_title": ("What it asked for", "Yêu cầu của ticket"),
    "verdict": ("Verdict", "Kết luận"),
    "verdict_words": ("Verdict, as the pack states it", "Kết luận, nguyên văn trong gói bằng chứng"),
    "status_when": ("Ticket status when verified", "Trạng thái ticket khi kiểm thử"),
    "commit": ("Code under test (commit)", "Mã nguồn được kiểm (commit)"),
    "verified_at": ("Verified at", "Thời điểm kiểm thử"),
    "environment": ("Environment tested (name — url)", "Môi trường kiểm thử (tên — url)"),
    "oracle": ("Oracle — the written source of 'correct'",
               "Nguồn chuẩn — tài liệu quyết định thế nào là 'đúng'"),
    "surfaces": ("Surfaces exercised", "Bề mặt đã kiểm"),
    "folder": ("Evidence folder", "Thư mục bằng chứng"),

    "k_cases": ("Cases in pack", "Số case"),
    "k_exec": ("Executed", "Đã chạy"),
    "k_pass": ("Passed", "Đạt"),
    "k_fail": ("Failed", "Không đạt"),
    "k_blocked": ("Blocked", "Bị chặn"),
    "k_rate": ("Pass rate", "Tỉ lệ đạt"),
    "bar": ("{bar}  {rate}% of the {n} case(s) that ran matched the cited expected value.",
            "{bar}  {rate}% trong {n} case đã chạy khớp với giá trị mong đợi đã dẫn nguồn."),
    "bar_none": ("No case ran. Nothing in this workbook is a verdict about the product.",
                 "Không case nào chạy được. Không có dòng nào trong file này là kết luận về sản phẩm."),

    "severity": ("Severity", "Mức độ"),
    "count": ("Count", "Số lượng"),
    "sev_means": ("What it means", "Nghĩa là gì"),
    "sev_handling": ("Handling", "Cách xử lý"),
    "total": ("Total", "Tổng"),
    "nd_row": ("A failed case that was never graded. Until someone grades it, it cannot be "
               "prioritised against anything else.",
               "Case không đạt nhưng chưa được đánh mức độ. Chưa đánh mức thì không thể xếp "
               "ưu tiên so với bất cứ việc gì."),
    "nd_handling": ("Grade it, then re-export", "Đánh mức độ rồi xuất lại"),
    "defects_here": ("The defects in this pack", "Các lỗi trong gói bằng chứng này"),
    "no_defects": ("No case in this pack is marked FAIL, so there is no defect to report.",
                   "Không case nào trong gói được đánh FAIL, nên không có lỗi nào để báo."),
    "worst": ("Worst severity found", "Mức nghiêm trọng nhất"),
    "worst_none": ("No defect carries a declared severity, so there is no worst one to name",
                   "Không lỗi nào có mức độ được khai, nên không thể nêu lỗi nặng nhất"),
    "sev_in_report": ("Severity the report states, in prose",
                      "Mức độ mà báo cáo nêu trong phần diễn giải"),
    "sev_in_report_note": ("Read out of REPORT.md, not out of a case record. It is shown because "
                           "the pack does declare it somewhere — but no case carries SEVERITY:, "
                           "so no defect row below can be graded, filtered or counted, and one "
                           "sentence cannot say which failed case it grades.",
                           "Đọc từ REPORT.md, không phải từ hồ sơ case. Hiện ở đây vì gói bằng "
                           "chứng có khai ở đâu đó — nhưng không case nào có SEVERITY:, nên không "
                           "dòng lỗi nào bên dưới có thể được đánh mức, lọc hay đếm, và một câu "
                           "văn không thể nói nó đang đánh mức cho case nào."),
    "conclusion": ("Conclusion", "Kết luận chi tiết"),

    "d_id": ("Defect ID", "Mã lỗi"),
    "d_summary": ("Summary — what is wrong", "Mô tả — sai ở đâu"),
    "d_priority": ("Priority (the product owner decides, not QA)",
                   "Ưu tiên (do product owner quyết định, không phải QA)"),
    "d_origin": ("Origin", "Nguồn gốc"),
    "d_status": ("Status", "Trạng thái"),
    "d_case": ("Found in case", "Phát hiện ở case"),
    "d_req": ("Requirement violated", "Yêu cầu bị vi phạm"),
    "d_steps": ("Steps to reproduce", "Các bước tái hiện"),
    "d_expected": ("Expected, per the cited source", "Mong đợi, theo nguồn đã dẫn"),
    "d_actual": ("Actual", "Thực tế"),
    "d_evidence": ("Evidence", "Bằng chứng"),
    "d_reco": ("Recommendation", "Đề xuất"),
    "reco_ticket_wide": ("(written about the ticket as a whole, not about this defect alone) {text}",
                         "(viết cho cả ticket, không riêng lỗi này) {text}"),

    "c_id": ("Case ID", "Mã case"),
    "c_title": ("Test case title", "Tên test case"),
    "c_kind": ("Kind — why this case exists", "Loại — vì sao có case này"),
    "c_type": ("Interface", "Giao diện"),
    "c_actor": ("Executed as (account, role)", "Chạy dưới tài khoản / vai"),
    "c_pre": ("Preconditions", "Điều kiện tiên quyết"),
    "c_entry": ("Entry point — how the user arrives", "Điểm vào — người dùng tới đó thế nào"),
    "c_steps": ("Test steps", "Các bước thực hiện"),
    "c_expected": ("Expected result", "Kết quả mong đợi"),
    "c_req": ("Requirement / citation", "Yêu cầu / nguồn dẫn"),
    "c_actual": ("Actual result", "Kết quả thực tế"),
    "c_status": ("Status", "Kết quả"),
    "c_after": ("State after the action (incl. after a reload)",
                "Trạng thái sau khi thao tác (kể cả sau khi tải lại)"),
    "c_back": ("Back / Cancel behaviour", "Hành vi Back / Cancel"),
    "c_evidence": ("Evidence files", "File bằng chứng"),

    "t_req": ("Requirement / citation", "Yêu cầu / nguồn dẫn"),
    "t_source": ("Where the citation came from", "Nguồn dẫn lấy từ đâu"),
    "t_case": ("Covered by case", "Được phủ bởi case"),
    "t_kind": ("Kind of coverage", "Loại phủ"),
    "t_result": ("Result", "Kết quả"),
    "t_defect": ("Defect", "Lỗi"),
    "t_expected": ("The expected value that was verified", "Giá trị mong đợi đã được kiểm"),
    "t_relative": ("Section numbers are relative to the oracle named on the Summary sheet: {oracle}. "
                   "A citation marked 'extracted' was read out of the case's EXPECTED line; a case "
                   "that declares REQUIREMENT: overrides that, and is the authoritative form.",
                   "Số mục là số theo tài liệu nguồn chuẩn nêu ở sheet Summary: {oracle}. Nguồn dẫn "
                   "ghi 'trích' là đọc từ dòng EXPECTED của case; case nào khai REQUIREMENT: thì "
                   "lấy theo khai báo đó, và đó mới là dạng chuẩn."),
    "t_holes": ("Cases that trace to nothing", "Case không truy vết được về yêu cầu nào"),
    "t_holes_note": ("An expected value with no cited source is the verifier's opinion. These "
                     "rows are the traceability holes in this verification.",
                     "Giá trị mong đợi không dẫn nguồn chỉ là ý kiến của người kiểm thử. Đây là "
                     "các lỗ hổng truy vết của lần kiểm thử này."),

    "e_no": ("#", "#"),
    "e_case": ("Case", "Case"),
    "e_file": ("File (click to open)", "File (bấm để mở)"),
    "e_shows": ("What this file shows", "File này cho thấy điều gì"),
    "e_kind": ("Kind", "Loại"),
    "e_size": ("Size", "Kích thước"),
    "e_note": ("Links are relative to this workbook, so they work while the workbook sits beside "
               "the evidence. Images are not committed to git — they live on the ticket.",
               "Đường dẫn là tương đối so với file này, nên chỉ hoạt động khi file nằm cạnh thư "
               "mục bằng chứng. Ảnh không được commit vào git — chúng nằm ở ticket."),

    "g_where": ("Where", "Ở đâu"),
    "g_what": ("What the pack does not say, and why it matters",
               "Gói bằng chứng chưa nói gì, và vì sao điều đó quan trọng"),
    "g_none": ("Nothing. Every field this report needs was declared in the pack.",
               "Không có. Mọi trường báo cáo này cần đều đã được khai trong gói bằng chứng."),
    "g_note": ("These are recorded, not guessed. A blank the tool filled in would read exactly "
               "like a fact somebody checked.",
               "Đây là ghi nhận, không phải phỏng đoán. Một ô do công cụ tự điền sẽ trông y như "
               "một sự thật đã có người kiểm."),

    "l_sheet": ("Sheet", "Sheet"),
    "l_answers": ("What it answers", "Trả lời câu hỏi gì"),
    "l_term": ("Term", "Thuật ngữ"),
    "l_means": ("What it means", "Nghĩa là gì"),
    "l_sheets": ("The six sheets", "Sáu sheet"),
    "l_status": ("Case status", "Kết quả của case"),
    "l_kind": ("Case kinds — the shapes a verification must include",
               "Loại case — các dạng bắt buộc phải có"),
    "l_origin": ("Origin — who the finding goes to",
                 "Nguồn gốc — lỗi này chuyển cho ai"),
    "sheet_sum": ("Is this ticket done, how many defects are there, and how bad is the worst one?",
                  "Ticket này xong chưa, có bao nhiêu lỗi, lỗi nặng nhất nặng đến đâu?"),
    "sheet_tc": ("What exactly was tested, by whom, with what expected value, and what happened?",
                 "Đã kiểm chính xác những gì, ai chạy, mong đợi gì, và thực tế ra sao?"),
    "sheet_df": ("What is wrong, how much does it hurt, and who fixes it?",
                 "Sai cái gì, thiệt hại đến đâu, ai sửa?"),
    "sheet_tr": ("Which requirement does each case actually check — and which cases check nothing?",
                 "Mỗi case thực sự kiểm yêu cầu nào — và case nào không kiểm yêu cầu nào cả?"),
    "sheet_ev": ("Where is the proof for each row above?",
                 "Bằng chứng cho từng dòng ở trên nằm ở đâu?"),
    "sheet_img": ("The annotated screenshots, embedded — the picture that carries each verdict.",
                  "Ảnh chụp có chú thích, nhúng sẵn — tấm ảnh mang kết luận của từng case."),
    "img_note": ("Each boxed screenshot from a case, embedded so the workbook stands alone — no "
                 "folder to open, nothing to lose when the images leave git. The caption is the "
                 "one drawn onto the image at capture time.",
                 "Mỗi ảnh có khung của từng case, nhúng thẳng vào đây để file tự đứng một mình — "
                 "không cần mở thư mục, không mất gì khi ảnh rời khỏi git. Chú thích chính là dòng "
                 "đã vẽ lên ảnh lúc chụp."),
    "img_none": ("No annotated screenshots in this pack. A non-UI verification (a migration, an "
                 "API check, a database read) proves itself with a recorded run, not a picture.",
                 "Gói này không có ảnh chụp chú thích. Một lần kiểm không giao diện (migration, "
                 "kiểm API, đọc cơ sở dữ liệu) tự chứng minh bằng bản ghi chạy, không phải bằng ảnh."),
    "img_caption": ("Case", "Case"),
    "bdd_scenario": ("Scenario", "Kịch bản"),
    "bdd_given": ("Given", "Cho trước"),
    "bdd_when": ("When", "Khi"),
    "bdd_and": ("and", "và"),
    "bdd_then": ("Then", "Thì"),
    "bdd_result": ("In fact", "Thực tế"),
    "bdd_step_shot": ("Step {n} {dash} {what}", "Bước {n} {dash} {what}"),
    "bdd_verdict_shot": ("Result {dash} {what}", "Kết quả {dash} {what}"),
    "priority_note": ("The product owner decides", "Do product owner quyết định"),
    "blocked_prefix": ("BLOCKED — nothing was verified. Reason: {reason}",
                       "BỊ CHẶN — chưa kiểm được gì. Lý do: {reason}"),
    "unblock": ("To unblock: {unblock}", "Để tháo chặn: {unblock}"),
    "req_declared": ("declared in the case record", "khai trong hồ sơ case"),
    "req_extracted": ("extracted from the case's EXPECTED line",
                      "trích từ dòng EXPECTED của case"),
}

SHEET_NAMES = ("Summary", "Test Cases", "Defects", "Traceability", "Evidence", "Evidence images")
LANGS = ("en", "vi")


class Labels(object):
    """`lang` picks the column headers; anything outside LANGS falls back to
    English and says so, because a half-translated report is worse than one."""

    def __init__(self, lang):
        self.lang = lang if lang in LANGS else "en"
        self.requested = lang
        self.fellback = self.lang != (lang or "en")

    def __call__(self, key, **kw):
        pair = _T.get(key)
        if not pair:
            return key
        text = pair[1] if self.lang == "vi" else pair[0]
        return text.format(**kw) if kw else text

    def h(self, key, **kw):
        """A column header or section title: local first, the international term
        in brackets when they differ."""
        local = self(key, **kw)
        if self.lang == "en":
            return local
        english = _T[key][0].format(**kw) if kw else _T[key][0]
        return local if english == local else "{} ({})".format(local, english)


# ---------------------------------------------------------------------------
# small helpers
# ---------------------------------------------------------------------------
def declared(value, style="cell"):
    """A cell that says NOT DECLARED rather than sitting empty. An empty cell
    reads as "nothing to say here"; this one reads as "nobody said"."""
    text = str(value or "").strip()
    return S(text, style) if text else S(NOT_DECLARED, "muted")


def declared_value(value, style="cell"):
    """EXPECTED and ACTUAL cells. "works as expected" is present and says
    nothing — the reader cannot tell what the screen was supposed to read — so
    it prints as NOT DECLARED, exactly like a missing value, and the gap under
    section 5 says which case wrote it. See docs/qa/method/case-writing.md."""
    text = str(value or "").strip()
    if text and VAGUE_VALUE.match(text):
        return S(NOT_DECLARED, "muted")
    return declared(text, style)


def dash(value, style="cell_center"):
    text = str(value or "").strip()
    return S(text, style) if text else S(DASH, "dash")


def result_style(result):
    return {"PASS": "pass", "FAIL": "fail", "BLOCKED": "blocked"}.get(result, "muted")


def severity_style(severity):
    return {"Blocker": "blocker", "Critical": "critical",
            "Major": "major", "Minor": "minor"}.get(severity, "muted")


def verdict_style(verdict):
    if verdict == "PASS":
        return "pass"
    if verdict in ("FAIL", "NEW-BUG"):
        return "fail"
    if verdict in ("PARTIAL", "UNCLEAR"):
        return "major"
    if verdict == "BLOCKED":
        return "blocked"
    return "muted"


def human_size(n):
    if n < 1024:
        return "{} B".format(n)
    if n < 1024 * 1024:
        return "{:.1f} KB".format(n / 1024.0)
    return "{:.1f} MB".format(n / (1024.0 * 1024.0))


def bar(rate, width=22):
    filled = int(round(width * max(0, min(100, rate)) / 100.0))
    return "█" * filled + "░" * (width - filled)


def bullets(items):
    return "\n".join("• {}".format(i) for i in items)


def numbered(items):
    if not items:
        return ""
    if len(items) == 1 and not re.match(r"^\s*\d+[.)]", items[0]):
        return items[0]
    return "\n".join(re.sub(r"^\s*(\d+)[.)]\s*", r"\1. ", i) for i in items)


def link_for(evidence, out_dir):
    try:
        rel = os.path.relpath(evidence.abs, out_dir)
    except ValueError:
        return None
    return rel.replace(os.sep, "/")


def evidence_summary(case, limit=6):
    names = [e.rel for e in case.evidence if e.rel.split("/")[-1] != "manifest.md"]
    if not names:
        return ""
    shown = names[:limit]
    text = "\n".join(shown)
    if len(names) > len(shown):
        text += "\n… and {} more (see the Evidence sheet)".format(len(names) - len(shown))
    return text


# ---------------------------------------------------------------------------
# sheet 1 — Summary
# ---------------------------------------------------------------------------
SUM_W = [32, 13, 13, 13, 13, 13, 22, 40]


def _mw(c1, c2):
    return sum(SUM_W[c1 - 1:c2])


def _pair(sh, label, cell, height=None):
    """A label/value row. The label is merged-free but the value is merged, and
    a merged cell never auto-fits — so the row is sized for whichever of the
    two needs more lines. Sizing for the value alone clipped every label that
    wrapped."""
    r = sh.row([S(label, "label"), cell])
    sh.merge(r, 2, r, 8)
    sh.rows[r - 1] = (sh.rows[r - 1][0],
                      height or max(est_height(label, SUM_W[0] - 2, min_pt=17.0),
                                    est_height(cell.value, _mw(2, 8), min_pt=17.0)))
    return r


def _section(sh, title):
    sh.blank(8.0)
    r = sh.row([S(title, "section")], 22.0)
    sh.merge(r, 1, r, 8)
    return r


def build_summary(wb, pack, L, out_dir):
    sh = wb.sheet(SHEET_NAMES[0], widths=SUM_W)
    counts = pack.counts
    sev = pack.severity_counts

    r = sh.row([S("{} {} {}".format(pack.key, DASH, L("wb_title")), "title")], 30.0)
    sh.merge(r, 1, r, 8)
    r = sh.row([S(pack.title or L("untitled"), "subtitle")], 20.0)
    sh.merge(r, 1, r, 8)

    # The answer, before anything else and above any page break. A severity
    # table three sections down is the right table on the wrong page.
    graded = " · ".join("{} {}".format(sev[x], x) for x in SEVERITIES if sev.get(x))
    if not pack.defects:
        tail = ""
    elif graded:
        tail = " — {}{}".format(graded, L("sev_worst", worst=pack.worst_severity))
    else:
        tail = L("sev_none_graded")
    headline = L("headline", verdict=pack.verdict or NOT_DECLARED, cases=counts["cases"],
                 npass=counts["pass"], nfail=counts["fail"], nblocked=counts["blocked"],
                 ndefects=len(pack.defects), sev=tail)
    r = sh.row([S(headline, verdict_style(pack.verdict) if pack.verdict else "muted")], 24.0)
    sh.merge(r, 1, r, 8)

    try:
        where = os.path.relpath(pack.dir)
    except ValueError:
        where = pack.dir
    if where.startswith(".."):
        where = pack.dir
    note = "{}\n{}".format(L("standard"), L("generated", evd=where, nd=NOT_DECLARED))
    r = sh.row([S(note, "note")], est_height(note, _mw(1, 8), min_pt=30.0, line_pt=12.0))
    sh.merge(r, 1, r, 8)

    # -- 1. identity ---------------------------------------------------------
    _section(sh, L.h("s1"))
    _pair(sh, L.h("ticket"), S(pack.key, "bold"))
    _pair(sh, L.h("ticket_title"), declared(pack.title))
    _pair(sh, L.h("verdict"), S(pack.verdict or NOT_DECLARED,
                                verdict_style(pack.verdict) if pack.verdict else "muted"), 20.0)
    if pack.verdict_note:
        _pair(sh, L.h("verdict_words"), S(pack.verdict_note, "info"))
    _pair(sh, L.h("status_when"), declared(pack.status))
    _pair(sh, L.h("commit"), declared(pack.commit, "mono"))
    _pair(sh, L.h("verified_at"), declared(pack.verified_at, "mono"))
    _pair(sh, L.h("environment"), declared(pack.environment))
    _pair(sh, L.h("oracle"), declared(pack.oracle))
    _pair(sh, L.h("surfaces"), declared(pack.surfaces))
    _pair(sh, L.h("folder"), S(os.path.basename(pack.dir), "mono"))

    # -- 2. execution --------------------------------------------------------
    _section(sh, L.h("s2"))
    sh.row([S(L.h("k_cases"), "header"), S(L.h("k_exec"), "header"), S(L.h("k_pass"), "header"),
            S(L.h("k_fail"), "header"), S(L.h("k_blocked"), "header"), S(L.h("k_rate"), "header"),
            B("header"), B("header")], 30.0)
    r = sh.row([N(counts["cases"], "kpi"), N(counts["executed"], "kpi"),
                N(counts["pass"], "kpi_pass"), N(counts["fail"], "kpi_fail"),
                N(counts["blocked"], "kpi_blocked"),
                S("{}%".format(counts["rate"]) if counts["executed"] else DASH, "kpi"),
                B("default"), B("default")], 28.0)
    text = (L("bar", bar=bar(counts["rate"]), rate=counts["rate"], n=counts["executed"])
            if counts["executed"] else L("bar_none"))
    r = sh.row([S(text, "bar")], 20.0)
    sh.merge(r, 1, r, 8)

    # -- 3. defects ----------------------------------------------------------
    _section(sh, L.h("s3"))
    sh.row([S(L.h("severity"), "header"), S(L.h("count"), "header"),
            S(L.h("sev_means"), "header"), B("header"), B("header"),
            S(L.h("sev_handling"), "header"), B("header"), B("header")], 30.0)
    r0 = len(sh.rows)
    sh.merge(r0, 3, r0, 5)
    sh.merge(r0, 6, r0, 8)
    for name in SEVERITIES:
        meaning, handling = SEVERITY_MEANING[name]
        n = sev.get(name, 0)
        r = sh.row([S(name, severity_style(name)), N(n, "num"), S(meaning, "cell"),
                    None, None, S(handling, "cell"), None, None],
                   est_height(meaning, _mw(3, 5), min_pt=17.0))
        sh.merge(r, 3, r, 5)
        sh.merge(r, 6, r, 8)
    if sev.get(NOT_DECLARED):
        r = sh.row([S(NOT_DECLARED, "muted"), N(sev[NOT_DECLARED], "num"),
                    S(L("nd_row"), "cell"), None, None, S(L("nd_handling"), "cell"), None, None],
                   est_height(L("nd_row"), _mw(3, 5), min_pt=17.0))
        sh.merge(r, 3, r, 5)
        sh.merge(r, 6, r, 8)
    worst = ("{}: {}".format(L("worst"), pack.worst_severity) if pack.worst_severity
             else L("worst_none") if pack.defects else "{}: {}".format(L("worst"), DASH))
    r = sh.row([S(L.h("total"), "bold"), N(len(pack.defects), "num"),
                S(worst, severity_style(pack.worst_severity) if pack.worst_severity else "muted"),
                None, None, B("cell"), None, None], 18.0)
    sh.merge(r, 3, r, 5)
    sh.merge(r, 6, r, 8)

    if pack.report_severities and any(not d.severity for d in pack.defects):
        stated = " / ".join(pack.report_severities)
        r = sh.row([S(L.h("sev_in_report"), "label"),
                    S(stated, severity_style(pack.report_severities[0])),
                    S(L("sev_in_report_note"), "cell"), None, None, None, None, None],
                   est_height(L("sev_in_report_note"), _mw(3, 8), min_pt=17.0))
        sh.merge(r, 3, r, 8)

    sh.blank(6.0)
    r = sh.row([S(L.h("defects_here"), "plain_bold")], 17.0)
    sh.merge(r, 1, r, 8)
    if pack.defects:
        sh.row([S(L.h("d_id"), "header"), S(L.h("severity"), "header"),
                S(L.h("d_summary"), "header"), B("header"), B("header"),
                S(L.h("d_origin"), "header"), S(L.h("d_case"), "header"),
                S(L.h("d_status"), "header")], 30.0)
        r0 = len(sh.rows)
        sh.merge(r0, 3, r0, 5)
        for d in pack.defects:
            r = sh.row([S(d.id, "mono"),
                        S(d.severity or NOT_DECLARED,
                          severity_style(d.severity) if d.severity else "muted"),
                        declared(d.summary), None, None,
                        S(d.origin or NOT_DECLARED, "cell_center" if d.origin else "muted"),
                        S(d.case, "cell_center"), S(d.status, "cell_center")],
                       est_height(d.summary, _mw(3, 5), min_pt=17.0))
            sh.merge(r, 3, r, 5)
    else:
        r = sh.row([S(L("no_defects"), "pass")], 18.0)
        sh.merge(r, 1, r, 8)

    # -- 4. the answer -------------------------------------------------------
    _section(sh, L.h("s4"))
    for label, value in ((L.h("conclusion"), pack.conclusion),
                         (L.h("d_reco"), pack.recommendation)):
        if not value:
            continue
        r = sh.row([S(label, "label"), S(value, "cell")],
                   est_height(value, _mw(2, 8), min_pt=17.0))
        sh.merge(r, 2, r, 8)

    # -- 5. declared unknowns ------------------------------------------------
    _section(sh, L.h("s5"))
    r = sh.row([S(L("g_note"), "note")], est_height(L("g_note"), _mw(1, 8), min_pt=17.0,
                                                    line_pt=12.0))
    sh.merge(r, 1, r, 8)
    if pack.gaps:
        sh.row([S(L.h("g_where"), "header"), S(L.h("g_what"), "header"), B("header"), B("header"),
                B("header"), B("header"), B("header"), B("header")], 26.0)
        r0 = len(sh.rows)
        sh.merge(r0, 2, r0, 8)
        for where, what in pack.gaps:
            r = sh.row([S(where, "mono"), S(what, "cell"), None, None, None, None, None, None],
                       est_height(what, _mw(2, 8), min_pt=17.0))
            sh.merge(r, 2, r, 8)
    else:
        r = sh.row([S(L("g_none"), "pass")], 18.0)
        sh.merge(r, 1, r, 8)

    # -- 6. how to read ------------------------------------------------------
    _section(sh, L.h("s6"))

    def legend(title, header_a, header_b, rows):
        r = sh.row([S(title, "plain_bold")], 17.0)
        sh.merge(r, 1, r, 8)
        sh.row([S(header_a, "header"), S(header_b, "header"), B("header"), B("header"),
                B("header"), B("header"), B("header"), B("header")], 22.0)
        r0 = len(sh.rows)
        sh.merge(r0, 2, r0, 8)
        for a, b, style in rows:
            r = sh.row([S(a, style), S(b, "cell"), None, None, None, None, None, None],
                       est_height(b, _mw(2, 8), min_pt=17.0))
            sh.merge(r, 2, r, 8)
        sh.blank(6.0)

    legend(L.h("l_sheets"), L.h("l_sheet"), L.h("l_answers"),
           [(SHEET_NAMES[0], L("sheet_sum"), "bold"),
            (SHEET_NAMES[1], L("sheet_tc"), "bold"),
            (SHEET_NAMES[2], L("sheet_df"), "bold"),
            (SHEET_NAMES[3], L("sheet_tr"), "bold"),
            (SHEET_NAMES[4], L("sheet_ev"), "bold"),
            (SHEET_NAMES[5], L("sheet_img"), "bold")])
    legend(L.h("l_status"), L.h("l_term"), L.h("l_means"),
           [(r_, RESULT_MEANING[r_], result_style(r_)) for r_ in CASE_RESULTS])
    legend(L.h("l_kind"), L.h("l_term"), L.h("l_means"),
           [(k, KIND_MEANING[k], "bold") for k in KINDS])
    legend(L.h("l_origin"), L.h("l_term"), L.h("l_means"),
           [(o, ORIGIN_MEANING[o], "bold") for o in ORIGINS])
    return sh


# ---------------------------------------------------------------------------
# sheet 2 — Test Cases
# ---------------------------------------------------------------------------
TC_W = [9, 38, 17, 11, 14, 24, 32, 32, 44, 44, 22, 44, 11, 12, 10, 32, 26, 30]


def build_cases(wb, pack, L, out_dir):
    sh = wb.sheet(SHEET_NAMES[1], widths=TC_W, freeze=(4, 2), fit_width=False)
    r = sh.row([S("{} {} {}".format(pack.key, DASH, L.h("sheet_tc")), "title")], 26.0)
    sh.merge(r, 1, r, len(TC_W))
    note = "{}  {}".format(_T["c_expected"][0] + ": ISO/IEC/IEEE 29119-3 §7.", L("g_note"))
    r = sh.row([S(note, "note")], 16.0)
    sh.merge(r, 1, r, len(TC_W))
    sh.blank(6.0)

    header = ["c_id", "c_title", "c_kind", "c_type", "d_priority", "c_actor", "c_pre", "c_entry",
              "c_steps", "c_expected", "c_req", "c_actual", "c_status", "severity", "d_origin",
              "c_after", "c_back", "c_evidence"]
    sh.row([S(L.h(k), "header") for k in header], 40.0)
    head_row = len(sh.rows)

    for case in pack.cases:
        actual = case.get("ACTUAL")
        if case.result == "BLOCKED":
            parts = [L("blocked_prefix", reason=case.reason or NOT_DECLARED)]
            if case.unblock:
                parts.append(L("unblock", unblock=case.unblock))
            if actual:
                parts.append(actual)
            actual = "\n".join(parts)

        req = "\n".join(case.requirements) if case.requirements else ""
        cells = [
            S(case.name, "mono"),
            declared(case.title, "bold"),
            dash(case.kind, "cell"),
            S(case.surface, "cell_center"),
            dash(case.priority, "cell"),
            declared(case.get("AS")),
            declared(case.get("PRECONDITION")),
            declared(case.get("ENTRY")),
            declared(numbered(case.steps)),
            declared_value(case.get("EXPECTED")),
            declared(req),
            declared_value(actual),
            S(case.result or NOT_DECLARED,
              result_style(case.result) if case.result else "muted"),
            S(case.severity, severity_style(case.severity)) if case.severity
            else (S(NOT_DECLARED, "muted") if case.result == "FAIL" else S(DASH, "dash")),
            S(case.origin, "cell_center") if case.origin
            else (S(NOT_DECLARED, "muted") if case.result == "FAIL" else S(DASH, "dash")),
            S(case.get("AFTER"), "cell") if case.get("AFTER")
            else (S(DASH, "dash") if case.non_ui else S(NOT_DECLARED, "muted")),
            S(case.get("BACK"), "cell") if case.get("BACK")
            else (S(DASH, "dash") if case.non_ui else S(NOT_DECLARED, "muted")),
            declared(evidence_summary(case), "mono"),
        ]
        sh.row(cells)

    sh.autofilter = "{}:{}".format(xlsx.ref(head_row, 1),
                                   xlsx.ref(max(head_row, len(sh.rows)), len(TC_W)))
    return sh


# ---------------------------------------------------------------------------
# sheet 3 — Defects
# ---------------------------------------------------------------------------
DF_W = [13, 46, 12, 16, 11, 11, 12, 26, 46, 44, 44, 34, 40]


def build_defects(wb, pack, L, out_dir):
    sh = wb.sheet(SHEET_NAMES[2], widths=DF_W, freeze=(4, 2), fit_width=False)
    r = sh.row([S("{} {} {}".format(pack.key, DASH, L.h("sheet_df")), "title")], 26.0)
    sh.merge(r, 1, r, len(DF_W))
    r = sh.row([S("ISO/IEC/IEEE 29119-3 §9 incident report. " + L("g_note"), "note")], 16.0)
    sh.merge(r, 1, r, len(DF_W))
    sh.blank(6.0)

    header = ["d_id", "d_summary", "severity", "d_priority", "d_origin", "d_status", "d_case",
              "d_req", "d_steps", "d_expected", "d_actual", "d_evidence", "d_reco"]
    sh.row([S(L.h(k), "header") for k in header], 40.0)
    head_row = len(sh.rows)

    if not pack.defects:
        r = sh.row([S(L("no_defects"), "pass")], 20.0)
        sh.merge(r, 1, r, len(DF_W))
        return sh

    for d in pack.defects:
        sh.row([
            S(d.id, "mono"),
            declared(d.summary, "bold"),
            S(d.severity or NOT_DECLARED,
              severity_style(d.severity) if d.severity else "muted"),
            dash(d.priority, "cell"),
            S(d.origin or NOT_DECLARED, "cell_center" if d.origin else "muted"),
            S(d.status, "cell_center"),
            S(d.case, "cell_center"),
            declared("\n".join(d.requirements)),
            declared(numbered(d.steps)),
            declared(d.expected),
            declared(d.actual),
            declared("\n".join(e.rel for e in d.evidence
                               if e.rel.split("/")[-1] != "manifest.md"), "mono"),
            declared(L("reco_ticket_wide", text=d.recommendation)
                     if d.recommendation and d.recommendation_is_ticket_wide
                     else d.recommendation),
        ])
    sh.autofilter = "{}:{}".format(xlsx.ref(head_row, 1),
                                   xlsx.ref(len(sh.rows), len(DF_W)))
    return sh


# ---------------------------------------------------------------------------
# sheet 4 — Traceability
# ---------------------------------------------------------------------------
TR_W = [36, 30, 14, 20, 12, 14, 60]


def build_traceability(wb, pack, L, out_dir):
    sh = wb.sheet(SHEET_NAMES[3], widths=TR_W, freeze=(4, 1))
    r = sh.row([S("{} {} {}".format(pack.key, DASH, L.h("sheet_tr")), "title")], 26.0)
    sh.merge(r, 1, r, len(TR_W))
    note = "Requirement traceability matrix. {}\n{}".format(
        L("g_note"), L("t_relative", oracle=pack.oracle or NOT_DECLARED))
    r = sh.row([S(note, "note")], est_height(note, sum(TR_W), min_pt=16.0, line_pt=12.0))
    sh.merge(r, 1, r, len(TR_W))
    sh.blank(6.0)

    sh.row([S(L.h(k), "header") for k in
            ("t_req", "t_source", "t_case", "t_kind", "t_result", "t_defect", "t_expected")], 40.0)
    head_row = len(sh.rows)

    defect_of = dict((d.case, d.id) for d in pack.defects)
    order = []
    rows = {}
    for case in pack.cases:
        for req in case.requirements:
            if req not in rows:
                order.append(req)
                rows[req] = []
            rows[req].append(case)

    for req in order:
        for case in rows[req]:
            sh.row([
                S(req, "bold"),
                S(L("req_declared") if case.req_source == "declared" else L("req_extracted"),
                  "muted"),
                S(case.name, "cell_center"),
                dash(case.kind, "cell"),
                S(case.result or NOT_DECLARED,
                  result_style(case.result) if case.result else "muted"),
                dash(defect_of.get(case.name), "cell_center"),
                declared_value(case.get("EXPECTED")),
            ])
    if order:
        sh.autofilter = "{}:{}".format(xlsx.ref(head_row, 1),
                                       xlsx.ref(len(sh.rows), len(TR_W)))

    holes = [c for c in pack.cases if not c.requirements]
    sh.blank(10.0)
    r = sh.row([S("{} ({})".format(L.h("t_holes"), len(holes)), "section")], 22.0)
    sh.merge(r, 1, r, len(TR_W))
    r = sh.row([S(L("t_holes_note"), "note")],
                est_height(L("t_holes_note"), sum(TR_W), min_pt=16.0, line_pt=12.0))
    sh.merge(r, 1, r, len(TR_W))
    if holes:
        for case in holes:
            r = sh.row([S(case.name, "mono"), declared(case.title, "bold"),
                        S(case.result or NOT_DECLARED,
                          result_style(case.result) if case.result else "muted"),
                        declared_value(case.get("EXPECTED")), None, None, None],
                       est_height(case.get("EXPECTED"), TR_W[3] + TR_W[4] + TR_W[5] + TR_W[6],
                                  min_pt=17.0))
            sh.merge(r, 2, r, 2)
            sh.merge(r, 4, r, 7)
    else:
        r = sh.row([S(L("g_none"), "pass")], 18.0)
        sh.merge(r, 1, r, len(TR_W))
    return sh


# ---------------------------------------------------------------------------
# sheet 5 — Evidence
# ---------------------------------------------------------------------------
EV_W = [6, 10, 46, 54, 26, 11]


def build_evidence(wb, pack, L, out_dir):
    sh = wb.sheet(SHEET_NAMES[4], widths=EV_W, freeze=(4, 0))
    r = sh.row([S("{} {} {}".format(pack.key, DASH, L.h("sheet_ev")), "title")], 26.0)
    sh.merge(r, 1, r, len(EV_W))
    r = sh.row([S(L("e_note"), "note")], 16.0)
    sh.merge(r, 1, r, len(EV_W))
    sh.blank(6.0)

    sh.row([S(L.h(k), "header") for k in
            ("e_no", "e_case", "e_file", "e_shows", "e_kind", "e_size")], 40.0)
    head_row = len(sh.rows)

    n = 0
    items = list(pack.pack_files)
    for case in pack.cases:
        items.extend(case.evidence)
    for e in items:
        n += 1
        target = link_for(e, out_dir)
        sh.row([N(n, "num"), S(e.case or DASH, "cell_center"),
                S(e.rel, "link" if target else "mono", link=target,
                  tooltip=e.note or None),
                declared(e.note), S(e.kind, "cell"), S(human_size(e.size), "cell_center")])
    if n:
        sh.autofilter = "{}:{}".format(xlsx.ref(head_row, 1),
                                       xlsx.ref(len(sh.rows), len(EV_W)))
    return sh


# ---------------------------------------------------------------------------
# sheet 6 — Evidence images: a step-by-step walkthrough, read as a scenario
#
# Not a wall of result screenshots. Each case is rendered as a Given/When/Then
# scenario a non-technical reader follows in plain language, then EVERY step's
# screenshot is embedded in the order it happened — so the sheet shows what was
# DONE, not only how it ended. The annotated result shot comes last, marked.
# ---------------------------------------------------------------------------
STEP_W = 760             # px: width a numbered step shot is drawn at
VERDICT_W = 900          # px: the annotated result gets more room
IMG_FALLBACK = (1280, 800)   # px: assumed shape when the bytes are not a readable PNG
PX_TO_PT = 0.75          # a screen pixel is 0.75 point tall — for the row that holds it

_STEP_NO = re.compile(r"(?:^|/)TC\d+_(\d+)_", re.I)
# A step marker "1." / "2)" at the start of a line OR inline after a space, so
# it splits both one-per-line STEPS and the compact "1. x  2. y  3. z" form.
_STEP_NUM_TEXT = re.compile(r"(?:^|\s)(\d{1,2})[.)]\s+")


def _shot_order(e):
    """Sort a case's screenshots the way they were taken: by step number, with
    the annotated (_boxed) result placed right after its own raw shot."""
    m = _STEP_NO.search(e.rel.replace("\\", "/"))
    step = int(m.group(1)) if m else 999
    return (step, 1 if "_boxed." in e.rel.lower() else 0)


def _shot_what(e):
    """A human phrase for what the file shows, from its name: the note the box
    carries if there is one, else the words baked into the filename."""
    if e.note:
        return e.note
    stem = e.rel.split("/")[-1].rsplit(".", 1)[0]
    stem = re.sub(r"^TC\d+_\d+_", "", stem)
    stem = stem.replace("_boxed", "").replace("_", " ").strip()
    return stem or e.rel.split("/")[-1]


def _gherkin(case, L):
    """Given / When / Then from the fields the case already carries: the actor
    and precondition are the Given, the numbered STEPS are the When, EXPECTED is
    the Then, and the ACTUAL is what in fact happened."""
    given = case.get("AS")
    pre = case.get("PRECONDITION")
    if pre:
        given = "{}, {}".format(given, pre) if given else pre
    raw_steps = case.get("STEPS")
    steps = [s.strip(" .") for s in _STEP_NUM_TEXT.split(raw_steps) if s.strip(" .")]
    # split() keeps the captured numbers as separate items; drop the bare digits
    steps = [s for s in steps if not s.isdigit()]
    if not steps and raw_steps:
        steps = [raw_steps.strip()]
    return {"given": given or NOT_DECLARED, "when": steps,
            "then": case.get("EXPECTED") or NOT_DECLARED,
            "fact": case.get("ACTUAL")}


def _embed(sh, data, name, descr, max_w):
    w0, h0 = xlsx.png_size(data) or IMG_FALLBACK
    scale = min(1.0, float(max_w) / w0) if w0 else 1.0
    dw, dh = int(w0 * scale), int(h0 * scale)
    band = sh.blank(dh * PX_TO_PT + 6.0)
    sh.image(data, band, 1, dw, dh, name=name, descr=(descr or name)[:250])


def build_evidence_images(wb, pack, L, out_dir):
    sh = wb.sheet(SHEET_NAMES[5], widths=[150], freeze=(2, 0), fit_width=False)
    r = sh.row([S("{} {} {}".format(pack.key, DASH, L.h("sheet_img")), "title")], 26.0)
    sh.merge(r, 1, r, 1)
    r = sh.row([S(L("img_note"), "note")], 30.0)
    sh.merge(r, 1, r, 1)

    cases_with_shots = [c for c in pack.cases
                        if any(e.rel.lower().endswith(".png") for e in c.evidence)]
    if not cases_with_shots:
        sh.blank(6.0)
        sh.row([S(L("img_none"), "muted")], 40.0)
        return sh

    for case in cases_with_shots:
        sh.blank(10.0)
        tc = case.name.split("_")[0].replace("TC", "TC ")
        title = case.title or case.name
        badge = " [{}]".format(case.result) if case.result else ""
        sh.row([S("{} {} {}{}".format(L.h("img_caption"), tc, DASH + " " + title, badge),
                  "section")], 22.0)

        # --- the scenario, in plain Given / When / Then --------------------
        g = _gherkin(case, L)
        sh.row([S("{}: {}".format(L.h("bdd_scenario"), title), "bold")], 16.0)
        sh.row([S("  {} {}".format(L.h("bdd_given"), g["given"]), "mono")], 15.0)
        for i, step in enumerate(g["when"]):
            kw = L.h("bdd_when") if i == 0 else L.h("bdd_and")
            sh.row([S("  {} {}".format(kw, step), "mono")], 15.0)
        sh.row([S("  {} {}".format(L.h("bdd_then"), g["then"]), "mono")], 15.0)
        if g["fact"]:
            sh.row([S("  {} {}".format(L.h("bdd_result"), g["fact"]), "mono")], 15.0)

        # --- every step's screenshot, in the order it happened -------------
        shots = sorted((e for e in case.evidence if e.rel.lower().endswith(".png")),
                       key=_shot_order)
        for e in shots:
            m = _STEP_NO.search(e.rel.replace("\\", "/"))
            boxed = "_boxed." in e.rel.lower()
            what = _shot_what(e)
            if boxed:
                cap = L("bdd_verdict_shot", dash=DASH, what=what)
            else:
                cap = L("bdd_step_shot", n=(m.group(1) if m else "?"), dash=DASH, what=what)
            sh.row([S(cap, "label" if boxed else "note")], 15.0)
            try:
                data = open(e.abs, "rb").read()
            except OSError:
                sh.row([S(e.rel + " — file not found beside the workbook", "muted")], 15.0)
                continue
            _embed(sh, data, case.name, cap, VERDICT_W if boxed else STEP_W)
    return sh


# ---------------------------------------------------------------------------
# export
# ---------------------------------------------------------------------------
def default_out(evd):
    key = os.path.basename(os.path.abspath(evd).rstrip(os.sep))
    return os.path.join(evd, "{}_testcases.xlsx".format(key))


def export(evd, out=None, lang=None, project=None):
    pack = evdpack.read_pack(evd, project=project)
    out = out or default_out(evd)
    out_dir = os.path.dirname(os.path.abspath(out)) or "."
    L = Labels(lang or (project or {}).get("language") or "en")

    wb = Workbook(title="{} — {}".format(pack.key, L("wb_title")), creator="ai-qa")
    build_summary(wb, pack, L, out_dir)
    build_cases(wb, pack, L, out_dir)
    build_defects(wb, pack, L, out_dir)
    build_traceability(wb, pack, L, out_dir)
    build_evidence(wb, pack, L, out_dir)
    build_evidence_images(wb, pack, L, out_dir)

    parent = os.path.dirname(os.path.abspath(out))
    if parent and not os.path.isdir(parent):
        os.makedirs(parent, exist_ok=True)
    wb.save(out)
    return pack, out, L


def _load_project():
    # vteam's ctx exposes Ctx().cfg(key, default) (ai-qa used ctx.load()/ctx.get);
    # project.language drives the workbook's header language, so this must work.
    if ctx is None:
        return {}
    try:
        c = ctx.Ctx()
        return {"name": str(c.cfg("project.name", "") or ""),
                "key": str(c.cfg("project.key", "") or ""),
                "language": str(c.cfg("project.language", "en") or "en")}
    except Exception:
        return {}


def main():
    ap = argparse.ArgumentParser(description="export an evidence pack to .xlsx")
    ap.add_argument("--evd", help="evidence folder, e.g. evd/SHOP-142")
    ap.add_argument("--out", default=None,
                    help="output path (default: <evd>/<TICKET>_testcases.xlsx)")
    ap.add_argument("--lang", default=None, choices=list(LANGS),
                    help="column-header language (default: project.language)")
    ap.add_argument("--strict", action="store_true",
                    help="exit 1 if the pack leaves anything the report needs undeclared")
    ap.add_argument("--selftest", action="store_true", help="prove this exporter can fail")
    args = ap.parse_args()

    if args.selftest:
        return selftest()
    if not args.evd:
        ap.error("--evd is required (or use --selftest)")

    if not os.path.isdir(args.evd):
        print("XLSX: BLOCKED  no such evidence folder: {}".format(args.evd))
        print("  This is a blocked run, not a failed export. Nothing was written.")
        return 2

    project = _load_project()
    try:
        pack, out, L = export(args.evd, args.out, args.lang, project)
    except OSError as exc:
        print("XLSX: BLOCKED  cannot write the workbook: {}".format(exc))
        return 2

    counts = pack.counts
    sev = pack.severity_counts
    print("XLSX: WROTE  {}".format(out))
    print("  {} sheets · {} case(s): {} pass · {} fail · {} blocked · {} defect(s)".format(
        len(SHEET_NAMES), counts["cases"], counts["pass"], counts["fail"],
        counts["blocked"], len(pack.defects)))
    graded = " · ".join("{} {}".format(sev[s], s) for s in SEVERITIES if sev.get(s))
    if graded:
        print("  severity: {}{}".format(graded, " · {} NOT DECLARED".format(sev[NOT_DECLARED])
                                        if sev.get(NOT_DECLARED) else ""))
    if L.fellback:
        print("  ! language {!r} is not translated — headers are in English".format(L.requested))
    if pack.gaps:
        print("  ! {} declared unknown(s), printed in the workbook's section 5:".format(
            len(pack.gaps)))
        for where, what in pack.gaps[:5]:
            print("      {}: {}".format(where, what.split(" — ")[0]))
        if len(pack.gaps) > 5:
            print("      … and {} more".format(len(pack.gaps) - 5))
        if args.strict:
            print("  --strict: the pack is not complete enough to report from.")
            return 1
    return 0


# ---------------------------------------------------------------------------
# selftest
#
# The exporter's failure mode is not a crash — it is a confident-looking cell.
# So the selftest asserts the file is a real workbook, and then mutates the
# pack one fact at a time and asserts the WORDING changed the way it must.
# ---------------------------------------------------------------------------
_CASE = """RESULT: PASS
KIND: acceptance
TITLE: A gold customer's 900,000 order gets 90,000 off
AS: customer "Tran Gold" (customer 1, tier gold)
PRECONDITION: customer 1 exists and its tier is gold, resolved read-only
ENTRY: signed in -> Orders -> New order -> place it
STEPS: 1. confirm tier gold  2. place one line of 900,000  3. read the priced order back
EXPECTED: discount 90,000 and total 810,000 — spec 3.2 R1, docs/spec/discounts.md 3.3
ACTUAL: discount 90,000, total 810,000
AFTER: the row shows 810,000 and the value survives a reload
BACK: Back returns to Orders with the filter intact
"""

_FAIL_CASE = """RESULT: FAIL
KIND: boundary
TITLE: An order of exactly 500,000 gets nothing off
FINDING: A gold order coming to exactly 500,000 VND receives no discount
SEVERITY: Major
ORIGIN: DEV
AS: customer "Tran Gold" (customer 1, tier gold)
PRECONDITION: customer 1 exists and its tier is gold, resolved read-only
ENTRY: signed in -> Orders -> New order -> place one line of exactly 500,000
STEPS: 1. place one line of 500,000  2. read the priced order back
EXPECTED: discount 50,000 and total 450,000 — spec 3.2 R1 ("500,000 VND or more")
ACTUAL: discount 0, total 500,000 — the customer was charged the full amount
AFTER: the wrong price is stored and is still wrong after a re-read
BACK: withdrawing the order worked normally
"""

_SCREEN_CASE = _CASE.replace("KIND: acceptance", "KIND: whole-screen").replace(
    "TITLE: A gold customer's 900,000 order gets 90,000 off",
    "TITLE: The neighbours — silver, no membership, and a refused order")

_REPORT = """# SHOP-142 — PARTIAL
COMMIT: 3d9d99d
VERIFIED-AT: 2026-09-04T08:25:41+00:00
ENVIRONMENT: stg — https://stg.demo-shop.example
ORACLE: docs/spec/discounts.md (Pricing specification, version 4, section 3.2)

## 1. What was asked for? (told as a user)

A gold customer should get 10% off once an order comes to 500,000 VND.

## 4. Conclusion

The discount works for ordinary orders. It is wrong in one place: an order of
exactly 500,000 VND gets nothing off.

**Finding — an order coming to exactly 500,000 VND gets nothing off**

- **Severity: Major.** A way around it exists: an order of 500,001 gets the
  discount normally.
- **Origin: DEV.** The document states the 500,000 case in a sentence written
  for that purpose, so this is a change to make in the product.

**Recommendation:** send it back for the rule that decides when the discount
starts, and add an order of exactly 500,000 to the developer's own checks.
"""

_MANIFEST = """# SHOP-142 — what was checked

TICKET: SHOP-142 — Apply the gold-tier loyalty discount at checkout
STATUS WHEN VERIFIED: Ready for QA
COMMIT: 3d9d99d (main, working tree clean)
VERIFIED-AT: 2026-09-04T08:26:30+00:00
ENVIRONMENT: stg — https://stg.demo-shop.example
ORACLE: docs/spec/discounts.md — Pricing specification, version 4, section 3
SURFACES: the ordering flow, and the stored order record read back read-only
VERDICT: PARTIAL — everything the ticket asked for holds as worded; the discount
is wrong for any basket that comes to exactly 500,000 VND. Severity Major.

## The cases

| Case | What it checks | Result |
|---|---|---|
| TC_1 | A gold customer's 900,000 order gets 90,000 off | PASS |
| TC_2 | An order of exactly 500,000 — the value the document names | **FAIL** |
| TC_3 | The neighbours still behave | PASS |
"""


# A case folder names what it proves; the sheet still cites the number.
C3 = "TC_3_the_neighbours_still_behave"


def _fixture(root):
    import shutil
    if os.path.exists(root):
        shutil.rmtree(root)
    os.makedirs(root)
    for name, text in (("manifest.md", _MANIFEST), ("REPORT.md", _REPORT),
                       ("verifysheet.md", "EXPECTED per spec 3.2 R1\n"),
                       ("debate.md", "verifier card\nchallenger card\nresolution\n"),
                       ("ticket.md", "# SHOP-142 — Apply the gold-tier loyalty discount\n")):
        with open(os.path.join(root, name), "w", encoding="utf-8") as fh:
            fh.write(text)
    for case, manifest in (("TC_1", _CASE), ("TC_2", _FAIL_CASE),
                           (C3, _SCREEN_CASE)):
        d = os.path.join(root, case)
        os.makedirs(d)
        with open(os.path.join(d, "manifest.md"), "w", encoding="utf-8") as fh:
            fh.write(manifest + "\n## What the files show\n\n"
                     "- `response.json` — the priced order the product returned\n")
        with open(os.path.join(d, "response.json"), "w", encoding="utf-8") as fh:
            fh.write('{"discount": 0}\n')
        for fn in ("01_orders_list.png", "03_total_boxed.png"):
            with open(os.path.join(d, fn), "wb") as fh:
                fh.write(b"\x89PNG\r\n\x1a\n")
    return root


def _rewrite(root, rel, fn):
    path = os.path.join(root, rel)
    with open(path, "r", encoding="utf-8") as fh:
        text = fh.read()
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(fn(text))


def _sheet_cells(path, index):
    """One sheet's cells as {"A4": "text"}, read back out of the saved workbook.
    Asserting on the file rather than on the objects that produced it is the
    whole point: a builder can be right while the writer drops the cell."""
    import zipfile
    from xml.etree import ElementTree
    with zipfile.ZipFile(path) as z:
        xml = z.read("xl/worksheets/sheet{}.xml".format(index)).decode("utf-8")
    ns = "{http://schemas.openxmlformats.org/spreadsheetml/2006/main}"
    out = {}
    for c in ElementTree.fromstring(xml).iter(ns + "c"):
        node = c.find(ns + "is/" + ns + "t")
        if node is None:
            node = c.find(ns + "v")
        if node is not None and node.text is not None:
            out[c.get("r")] = node.text
    return out


def _sheet_text(path, index):
    """The visible text of one sheet, in row order."""
    cells = _sheet_cells(path, index)
    return "\n".join(cells[k] for k in sorted(
        cells, key=lambda r: (int(re.sub(r"[A-Z]", "", r)), re.sub(r"\d", "", r))))


def _column(path, index, letter):
    cells = _sheet_cells(path, index)
    return [v for k, v in sorted(cells.items(), key=lambda kv: int(re.sub(r"[A-Z]", "", kv[0])))
            if re.sub(r"\d", "", k) == letter]


def selftest():
    import shutil
    import tempfile
    import zipfile
    from xml.etree import ElementTree

    tmp = tempfile.mkdtemp(prefix="aiqa-xlsx-")
    fails = []

    def expect(cond, msg):
        if not cond:
            fails.append(msg)

    def build(name, mutate=None, lang="en"):
        evd = _fixture(os.path.join(tmp, name, "SHOP-142"))
        if mutate:
            mutate(evd)
        pack, out, _L = export(evd, lang=lang)
        return pack, out

    # 1. it is a real workbook -------------------------------------------------
    pack, out = build("green")
    expect(os.path.getsize(out) > 4000, "the workbook is suspiciously small")
    expect(zipfile.is_zipfile(out), "the output is not a zip container")
    with zipfile.ZipFile(out) as z:
        names = z.namelist()
        expect(z.testzip() is None, "the zip is corrupt")
        for required in ("[Content_Types].xml", "_rels/.rels", "xl/workbook.xml",
                         "xl/_rels/workbook.xml.rels", "xl/styles.xml"):
            expect(required in names, "the workbook is missing {}".format(required))
        for i in range(1, len(SHEET_NAMES) + 1):
            expect("xl/worksheets/sheet{}.xml".format(i) in names,
                   "sheet {} was not written".format(i))
        for name in names:
            if name.endswith((".xml", ".rels")):
                try:
                    ElementTree.fromstring(z.read(name))
                except Exception as exc:
                    expect(False, "{} is not well-formed XML: {}".format(name, exc))
        book = z.read("xl/workbook.xml").decode("utf-8")
        for sheet_name in SHEET_NAMES:
            expect('name="{}"'.format(sheet_name) in book,
                   "the workbook has no {} sheet".format(sheet_name))
        expect(len([n for n in names if n.startswith("xl/worksheets/_rels/")]) >= 1,
               "no sheet declared hyperlink relationships — the evidence links are dead")

        # The green fixture carries a *_boxed.png, so the workbook must actually
        # embed it: media bytes, a drawing that places them, and the png content
        # type. A link is not an embed — this proves the image is IN the file.
        media = [n for n in names if n.startswith("xl/media/") and n.endswith(".png")]
        expect(media, "a pack with an annotated screenshot embedded no image media")
        expect(any(n.startswith("xl/drawings/drawing") and n.endswith(".xml") for n in names),
               "image media with no drawing part — the picture is in the zip but anchored nowhere")
        ctypes = z.read("[Content_Types].xml").decode("utf-8")
        expect('Extension="png"' in ctypes,
               "png media with no content-type default — Excel will call the file corrupt")
        embedded = z.read(media[0])
        expect(embedded[:8] == b"\x89PNG\r\n\x1a\n" or len(embedded) >= 8,
               "the embedded media is not the image bytes")
        # The walkthrough shows the STEPS, not only the result: the green
        # fixture's case has a step shot AND a _boxed result, so more than one
        # image must be embedded per case's worth of pngs.
        expect(len(media) >= 2,
               "the walkthrough embedded only one image — the steps that show what was DONE are missing")

    # The image sheet reads as a Given/When/Then scenario a non-coder follows,
    # not a caption-less pile of screenshots.
    walk = _sheet_text(out, 6)
    for kw in ("Scenario", "Given", "When", "Then"):
        expect(kw in walk, "the walkthrough sheet is missing the '{}' line — it is not a readable "
                           "scenario".format(kw))
    expect("Step " in walk or "Result " in walk,
           "the walkthrough labels no step or result image — the reader cannot tell what each shows")

    # every style a builder asked for must exist in styles.xml
    expect(max(xlsx.STYLES.values()) + 1 == len(xlsx._XFS),
           "the style table and the style index disagree")

    # 2. the numbers are the pack's numbers ------------------------------------
    expect(pack.counts["cases"] == 3, "counted {} cases, expected 3".format(pack.counts["cases"]))
    expect(pack.counts["pass"] == 2 and pack.counts["fail"] == 1,
           "pass/fail counted {}/{}".format(pack.counts["pass"], pack.counts["fail"]))
    expect(len(pack.defects) == 1, "expected exactly 1 defect, got {}".format(len(pack.defects)))
    expect(pack.defects[0].severity == "Major", "the declared severity was not read back")
    expect(pack.defects[0].origin == "DEV", "the declared origin was not read back")
    expect(pack.worst_severity == "Major", "worst severity is {}".format(pack.worst_severity))
    expect(pack.verdict == "PARTIAL", "verdict read as {!r}".format(pack.verdict))
    expect(pack.commit == "3d9d99d", "COMMIT read as {!r}".format(pack.commit))
    expect(pack.environment == "stg — https://stg.demo-shop.example",
           "ENVIRONMENT read as {!r}".format(pack.environment))
    expect("500,000" in pack.conclusion, "the conclusion was not carried into the workbook")
    expect("**" not in pack.conclusion and "Recommendation" not in pack.conclusion,
           "the conclusion swallowed the finding and recommendation blocks that have their "
           "own sheets")
    # A wrapped paragraph has to arrive whole: the first line alone reads as a
    # complete sentence and says something the report does not.
    expect(pack.recommendation.startswith("send it back")
           and pack.recommendation.endswith("developer's own checks."),
           "the recommendation was cut off at its first line: {!r}".format(pack.recommendation))
    expect(not pack.gaps, "the green fixture declared gaps: {}".format(pack.gaps))

    # citations: one requirement, one row, however the case spelled it
    cite = evdpack.citations
    expect(cite("total 810,000 — spec 3.2 R1, docs/spec/discounts.md 3.3")
           == ["3.2 R1", "docs/spec/discounts.md 3.3"],
           "a citation followed by a comma, or a file citation, was lost: {}".format(
               cite("total 810,000 — spec 3.2 R1, docs/spec/discounts.md 3.3")))
    expect(cite("spec 3.2 R1") == cite("section 3.2 R1") == cite("3.2 R1") == ["3.2 R1"],
           "the same rule spelled three ways did not collapse to one requirement")
    expect(cite("499,999 gets no discount (3.2 R1) · 3,000,000 gets 100,000 (3.2 R2, the cap)")
           == ["3.2 R1", "3.2 R2"],
           "a rule id in brackets, with no the word 'spec' anywhere, was not found")
    expect(cite("the total is 1,000,005 and the order is 2 x 250,000") == [],
           "a money amount was read as a section number: {}".format(
               cite("the total is 1,000,005 and the order is 2 x 250,000")))
    expect(cite("discount 90,000 and total 810,000") == [],
           "an EXPECTED with no citation was given one")

    summary = _sheet_text(out, 1)
    defects = _sheet_text(out, 3)
    cases = _sheet_text(out, 2)
    trace = _sheet_text(out, 4)
    evidence = _sheet_text(out, 5)
    expect("PARTIAL" in summary, "the summary does not print the verdict")
    top = "\n".join(summary.split("\n")[:4])
    expect("PARTIAL" in top and "1 defect" in top and "Major" in top and "2 passed" in top,
           "the first four cells do not answer verdict / how many / how bad: {!r}".format(top))
    expect("Major" in summary and "Blocker" in summary,
           "the summary does not print the whole severity ladder")
    expect("SHOP-142-D1" in defects and "Major" in defects and "DEV" in defects,
           "the defect sheet is missing its identity, severity or origin")
    expect("exactly 500,000" in defects, "the defect summary did not reach the sheet")
    expect("send it back" in defects and "as a whole" not in defects,
           "with one defect the report's recommendation is that defect's recommendation")
    identity = summary.split(_T["s2"][0])[0].split(_T["s1"][0])[-1]
    expect(NOT_DECLARED not in identity,
           "the green fixture printed NOT DECLARED in its identity block")
    expect("3d9d99d" in identity and "discounts.md" in identity and "Ready for QA" in identity,
           "the identity block lost the commit, the oracle or the ticket status")
    expect("stg — https://stg.demo-shop.example" in identity,
           "the identity block does not say which environment the verdict came from")
    expect("TC_2" in cases and "boundary" in cases, "the boundary case is not in the sheet")
    expect("spec 3.2 R1" in trace, "the citation did not reach the traceability matrix")
    expect("response.json" in evidence, "the evidence index is empty")
    expect("SHOP-142-D1" in trace, "the traceability matrix does not link the defect")
    reqs = _column(out, 4, "A")
    expect(not any(r.lower().startswith(("spec ", "section ")) for r in reqs),
           "the traceability matrix carries a rule under an unnormalised spelling: {}".format(reqs))
    expect(reqs.count("3.2 R1") == len([c for c in pack.cases if "3.2 R1" in c.requirements]),
           "the requirement column does not carry one row per (requirement, case) pair")
    expect("discounts.md" in trace,
           "the traceability sheet does not say which document the section numbers belong to")

    # 3. deterministic: the same pack must produce the same bytes --------------
    out2 = os.path.join(tmp, "again.xlsx")
    export(pack.dir, out=os.path.join(tmp, "green", "SHOP-142", "again.xlsx"))
    export(pack.dir, out=out2)
    with open(os.path.join(tmp, "green", "SHOP-142", "again.xlsx"), "rb") as a:
        first = a.read()
    export(pack.dir, out=os.path.join(tmp, "green", "SHOP-142", "again.xlsx"))
    with open(os.path.join(tmp, "green", "SHOP-142", "again.xlsx"), "rb") as a:
        expect(a.read() == first, "two exports of the same pack differ byte for byte")

    # 4. every honesty rule must be able to fire ------------------------------
    mutations = [
        ("a FAIL case with no SEVERITY",
         lambda d: _rewrite(d, "TC_2/manifest.md", lambda t: t.replace("SEVERITY: Major\n", "")),
         lambda pack, text: (any("SEVERITY" in w for _w, w in pack.gaps)
                             and NOT_DECLARED in text[0]
                             and pack.severity_counts[NOT_DECLARED] == 1
                             # the report says Major in prose: shown as the report's
                             # statement, never promoted into the defect row
                             and pack.report_severities == ["Major"]
                             and "in prose" in text[0]
                             and "no worst one to name" in text[0]
                             # the headline must not claim a grade it does not have
                             and "none graded" in text[0])),
        ("a FAIL case with no ORIGIN",
         lambda d: _rewrite(d, "TC_2/manifest.md", lambda t: t.replace("ORIGIN: DEV\n", "")),
         lambda pack, text: any("ORIGIN" in w for _w, w in pack.gaps)),
        ("a severity outside the ladder",
         lambda d: _rewrite(d, "TC_2/manifest.md",
                            lambda t: t.replace("SEVERITY: Major", "SEVERITY: quite bad")),
         lambda pack, text: (pack.defects[0].severity == ""
                             and any("quite bad" in w for _w, w in pack.gaps))),
        ("an EXPECTED with no citation",
         lambda d: _rewrite(d, "TC_1/manifest.md",
                            lambda t: re.sub(r"(?m)^EXPECTED:.*$",
                                             "EXPECTED: it should look right", t)),
         lambda pack, text: (any("citation" in w for _w, w in pack.gaps)
                             and "TC_1" in text[3].split("trace to nothing")[-1])),
        ("a verdict that asserts a defect with no failed case",
         lambda d: _rewrite(d, "TC_2/manifest.md",
                            lambda t: t.replace("RESULT: FAIL", "RESULT: PASS")),
         lambda pack, text: (not pack.defects
                             and any("no case is marked RESULT: FAIL" in w for _w, w in pack.gaps))),
        ("a PASS verdict over a failed case",
         lambda d: _rewrite(d, "REPORT.md", lambda t: t.replace("— PARTIAL", "— PASS")),
         lambda pack, text: any("verdict is PASS" in w for _w, w in pack.gaps)),
        # The pack manifest carries the same header, and the reader falls back to
        # it on purpose — so the mutation has to remove both to prove the rule.
        ("no ORACLE line anywhere",
         lambda d: (_rewrite(d, "REPORT.md", lambda t: re.sub(r"(?m)^ORACLE:.*\n", "", t)),
                    _rewrite(d, "manifest.md", lambda t: re.sub(r"(?m)^ORACLE:.*\n", "", t))),
         lambda pack, text: any("no ORACLE" in w for _w, w in pack.gaps)),
        ("no ORACLE in the report, but the pack manifest has it",
         lambda d: _rewrite(d, "REPORT.md", lambda t: re.sub(r"(?m)^ORACLE:.*\n", "", t)),
         lambda pack, text: (pack.oracle.startswith("docs/spec/discounts.md")
                             and not any("no ORACLE" in w for _w, w in pack.gaps))),
        ("an ORACLE of NONE",
         lambda d: _rewrite(d, "REPORT.md",
                            lambda t: re.sub(r"(?m)^ORACLE:.*$", "ORACLE: NONE", t)),
         lambda pack, text: any("opinion, not a fact" in w for _w, w in pack.gaps)),
        ("no ENVIRONMENT line anywhere",
         lambda d: (_rewrite(d, "REPORT.md", lambda t: re.sub(r"(?m)^ENVIRONMENT:.*\n", "", t)),
                    _rewrite(d, "manifest.md", lambda t: re.sub(r"(?m)^ENVIRONMENT:.*\n", "", t))),
         lambda pack, text: any("no ENVIRONMENT" in w for _w, w in pack.gaps)),
        ("no ENVIRONMENT in the report, but the pack manifest has it",
         lambda d: _rewrite(d, "REPORT.md", lambda t: re.sub(r"(?m)^ENVIRONMENT:.*\n", "", t)),
         lambda pack, text: (pack.environment.startswith("stg")
                             and not any("no ENVIRONMENT" in w for _w, w in pack.gaps))),
        ("a missing REPORT.md",
         lambda d: os.remove(os.path.join(d, "REPORT.md")),
         lambda pack, text: (pack.verdict == "PARTIAL"  # falls back to the manifest's VERDICT
                             and any("REPORT.md" == w for w, _x in pack.gaps))),
        ("a case with no TITLE",
         lambda d: _rewrite(d, "TC_1/manifest.md",
                            lambda t: re.sub(r"(?m)^TITLE:.*\n", "", t)),
         # the root manifest's case table still names it, so nothing is lost
         lambda pack, text: (pack.cases[0].title.startswith("A gold customer")
                             and "case table" in pack.cases[0].title_source)),
        ("a case with no TITLE and no table row",
         lambda d: (_rewrite(d, "TC_1/manifest.md",
                             lambda t: re.sub(r"(?m)^TITLE:.*\n", "", t)),
                    _rewrite(d, "manifest.md",
                             lambda t: re.sub(r"(?m)^\| TC_1 .*\n", "", t))),
         lambda pack, text: any("no TITLE" in w for _w, w in pack.gaps)),
        # Two defects and one ticket-level recommendation: shown on both rows,
        # labelled, because advice written about the ticket is not advice about
        # a particular defect.
        ("a second failed case sharing one ticket-level recommendation",
         lambda d: _rewrite(d, C3 + "/manifest.md",
                            lambda t: t.replace("RESULT: PASS", "RESULT: FAIL\nSEVERITY: Minor\n"
                                                "ORIGIN: DEV")),
         lambda pack, text: (len(pack.defects) == 2
                             and all(d.recommendation_is_ticket_wide for d in pack.defects)
                             and text[2].count("as a whole") == 2
                             and "Minor" in text[0] and "worst: Major" in text[0])),
        ("an EXPECTED that is a judgement, not a value",
         lambda d: _rewrite(d, "TC_1/manifest.md",
                            lambda t: re.sub(r"(?m)^EXPECTED:.*$", "EXPECTED: works as expected", t)),
         lambda pack, text: (any("judgement, not a value" in w for _w, w in pack.gaps)
                             # the cases sheet prints NOT DECLARED where the wish was —
                             # a reader must not mistake "works" for a value
                             and NOT_DECLARED in text[1])),
        ("a BLOCKED case with no way out",
         lambda d: _rewrite(d, C3 + "/manifest.md",
                            lambda t: t.replace("RESULT: PASS", "RESULT: BLOCKED")),
         lambda pack, text: (any("UNBLOCK" in w for _w, w in pack.gaps)
                             and "BLOCKED" in text[1])),
        # Neither the case record nor the table names it — but the folder does,
        # and a folder called TC_3_the_neighbours_still_behave is a declaration.
        ("a case named only by its folder",
         lambda d: (_rewrite(d, C3 + "/manifest.md",
                             lambda t: re.sub(r"(?m)^TITLE:.*\n", "", t)),
                    _rewrite(d, "manifest.md",
                             lambda t: re.sub(r"(?m)^\| TC_3 .*\n", "", t))),
         lambda pack, text: (pack.cases[2].name == "TC_3"
                             and pack.cases[2].title == "the neighbours still behave"
                             and pack.cases[2].title_source == "the case folder name")),
    ]
    for i, (label, mutate, assert_fn) in enumerate(mutations):
        p, o = build("mut{}".format(i), mutate)
        texts = [_sheet_text(o, n) for n in range(1, 6)]
        try:
            held = bool(assert_fn(p, texts))
        except Exception as exc:  # an assertion that crashes is a failed assertion
            held = False
            label = "{} (assertion raised {})".format(label, exc)
        expect(held, "the exporter did not report: {}".format(label))
        expect(any(NOT_DECLARED in t for t in texts) or "no case is marked" in texts[0]
               or "trace to nothing" in texts[3] or "BLOCKED" in texts[1],
               "a mutated pack produced a workbook with nothing marked: {}".format(label))

    # 5. text that cannot go in a cell must be handled, not crash --------------
    def _huge(d):
        _rewrite(d, "TC_1/manifest.md",
                 lambda t: t.replace("ACTUAL: discount 90,000, total 810,000",
                                     "ACTUAL: " + ("x" * 40000)))

    p, o = build("huge", _huge)
    text = _sheet_text(o, 2)
    expect("[truncated" in text, "an over-long value was not truncated with a visible marker")
    expect(all(len(t) <= xlsx.CELL_LIMIT for t in text.split("\n")),
           "a cell longer than Excel's limit reached the file")

    def _control_chars(d):
        _rewrite(d, "TC_1/manifest.md",
                 lambda t: t.replace("ACTUAL: discount 90,000, total 810,000",
                                     "ACTUAL: \x1b[31mred\x1b[0m \x00 & <tag> \"quoted\""))

    p, o = build("ctrl", _control_chars)
    with zipfile.ZipFile(o) as z:
        for name in z.namelist():
            if name.endswith(".xml"):
                ElementTree.fromstring(z.read(name))  # raises if escaping failed
    expect("& <tag> \"quoted\"" in _sheet_text(o, 2),
           "escaping lost the characters it was supposed to preserve")

    # 6. the other language really changes the headers -------------------------
    _p, o = build("vi", lang="vi")
    vi = _sheet_text(o, 1)
    expect("Báo cáo test case" in vi, "the vi workbook is not in Vietnamese")
    expect("Mức độ (Severity)" in vi,
           "a translated header lost its English term — an outside reader cannot read it")
    expect("Major" in vi and "PARTIAL" in vi,
           "the vocabulary was translated; PASS/FAIL/Major are the tool's own words")

    # 7. an empty folder is BLOCKED, not a workbook full of blanks -------------
    empty = os.path.join(tmp, "empty", "SHOP-999")
    os.makedirs(empty)
    p, o, _L = export(empty)
    expect(any("no TC_" in w for _w, w in p.gaps), "an empty pack did not report having no cases")
    expect(os.path.exists(o), "an empty pack should still produce a readable, honest workbook")
    expect("no defect" in _sheet_text(o, 3).lower(),
           "an empty pack's defect sheet does not say it is empty")

    # 8. a sheet name Excel would reject is corrected --------------------------
    taken = set()
    expect(xlsx.safe_sheet_name("a/b:c*d?[e]", taken) == "a b c d  e",
           "an illegal sheet name was not sanitised")
    expect(xlsx.safe_sheet_name("x" * 40, taken) == "x" * 31, "a long sheet name was not trimmed")
    expect(xlsx.safe_sheet_name("Dup", taken) == "Dup"
           and xlsx.safe_sheet_name("Dup", taken) == "Dup 2", "duplicate sheet names collide")

    shutil.rmtree(tmp, ignore_errors=True)
    if fails:
        print("xlsx_export --selftest FAILED")
        for f in fails:
            print("  x {}".format(f))
        return 1
    print("xlsx_export --selftest passed  ({} honesty mutations, each one reported)".format(
        len(mutations)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
