#!/usr/bin/env python3
"""evd_index.py — make the evidence folder answer its own questions.

Two questions get asked of every evidence folder, usually months later by
somebody who was not there:

    what was actually tested here?      — and —      which case is this file from?

A tree of `TC_1/ TC_2/ TC_3/` answers neither. This writes the answer into
`evd/<TICKET>/manifest.md`, between markers, from the case manifests
themselves — so the index cannot drift from the evidence it describes. The
prose around the block is yours; only the block is regenerated.

    python3 .vteam/scripts/evd_index.py --evd evd/SHOP-142
    python3 .vteam/scripts/evd_index.py --evd evd/SHOP-142 --check   # exit 1 if stale

`evd_check.py` runs the same rendering and reds a manifest whose index no
longer matches the folder — an index that lies is worse than no index.

Prove it:  python3 evd_index.py --selftest
Python 3.9 compatible. No dependencies.
"""
import argparse
import os
import re
import sys

BEGIN = "<!-- vteam:index -->"
END = "<!-- /vteam:index -->"
CASE_DIR = re.compile(r"^TC_(\d+)(?:_(.+))?$")
STEP_IMAGE = re.compile(r"^(?:TC\d+_)?\d{2}_.+\.(?:png|jpg|jpeg)$", re.I)
BOXED = re.compile(r"_boxed\.(?:png|jpg|jpeg)$", re.I)


def read(path):
    try:
        with open(path, "r", encoding="utf-8", errors="replace") as fh:
            return fh.read()
    except Exception:
        return ""


def fields(text):
    """The same 'KEY: value' grammar the evidence gate reads, so a manifest
    that satisfies one is legible to the other."""
    out = {}
    for line in text.splitlines():
        m = re.match(r"^\s*(?:[-*]\s*)?([A-Z][A-Z_-]{1,20}):\s*(.*)$", line)
        if m and m.group(1).upper() not in out:
            out[m.group(1).upper()] = m.group(2).strip()
    return out


def cases(evd):
    """Every TC folder, in numeric order — TC_10 sorts after TC_9, which is
    where a plain sort quietly gets it wrong."""
    found = []
    for d in sorted(os.listdir(evd)) if os.path.isdir(evd) else []:
        m = CASE_DIR.match(d)
        if m and os.path.isdir(os.path.join(evd, d)):
            found.append((int(m.group(1)), m.group(2) or "", d))
    return sorted(found, key=lambda t: t[0])


def humanize(slug):
    return re.sub(r"[_-]+", " ", slug).strip()


def _escape(text):
    """A pipe inside a cell would split the row and silently lose a column."""
    return str(text).replace("|", "\\|").strip()


def title_of(slug, f):
    """What this case is FOR, in one line. TITLE: when the author wrote one —
    the same field the spreadsheet export reads — otherwise the folder name,
    which is why the folder name is required."""
    return f.get("TITLE") or humanize(slug) or "(unnamed — rename the folder TC_<n>_<what_it_proves>)"


def evidence_cell(evd, dirname):
    """Name the artefacts, not the count. 'which file do I open' is the whole
    reason someone is reading an index."""
    d = os.path.join(evd, dirname)
    names = sorted(os.listdir(d)) if os.path.isdir(d) else []
    bits = []
    boxed = [n for n in names if BOXED.search(n)]
    shots = [n for n in names if STEP_IMAGE.match(n) and not BOXED.search(n)]
    if boxed:
        bits.append("[{}]({}/{})".format(boxed[0], dirname, boxed[0]))
        if len(boxed) > 1:
            bits.append("+{} boxed".format(len(boxed) - 1))
    if shots:
        bits.append("{} shot{}".format(len(shots), "s" if len(shots) != 1 else ""))
    for extra in ("journey.mjs", "db_verify.md", "cmd_verify.md", "request.http", "response.json"):
        if extra in names:
            bits.append("[{}]({}/{})".format(extra, dirname, extra))
    return " · ".join(bits) or "—"


def render(evd):
    """The generated block. Deterministic: same folder, same bytes."""
    rows = []
    tally = {"PASS": 0, "FAIL": 0, "BLOCKED": 0, "OTHER": 0}
    for num, slug, dirname in cases(evd):
        f = fields(read(os.path.join(evd, dirname, "manifest.md")))
        result = (f.get("RESULT") or "?").upper()
        tally[result if result in tally else "OTHER"] += 1
        note = ""
        if result == "BLOCKED":
            # A blocked case that does not say why reads as a case nobody tried.
            note = " — {}".format(_escape(f.get("REASON") or f.get("BLOCKED_BY") or "no reason given"))
        rows.append("| **TC_{}** | {} | {} | {}{} | {} |".format(
            num,
            _escape(title_of(slug, f)),
            _escape(f.get("KIND") or "—"),
            result,
            note,
            evidence_cell(evd, dirname),
        ))

    total = sum(tally.values())
    summary = "{} case{} · {} PASS · {} FAIL · {} BLOCKED".format(
        total, "" if total == 1 else "s", tally["PASS"], tally["FAIL"], tally["BLOCKED"])

    out = [BEGIN,
           "<!-- generated by evd_index.py — edit the case manifests, then re-run it -->",
           "",
           "## What was verified",
           "",
           "| case | what it proves | kind | result | evidence |",
           "|---|---|---|---|---|"]
    out += rows or ["| — | *no TC_<n>_<what> folders yet* | — | — | — |"]
    out += ["", summary, END]
    return "\n".join(out) + "\n"


def apply(evd, text=None):
    """Replace the block, keeping every word around it. A manifest with no
    block yet gets one after the title, not at the end — an index below the
    tracker attachments is an index nobody scrolls to."""
    block = render(evd) if text is None else text
    path = os.path.join(evd, "manifest.md")
    cur = read(path)
    if BEGIN in cur and END in cur:
        head, rest = cur.split(BEGIN, 1)
        _, tail = rest.split(END, 1)
        return head + block.rstrip("\n") + tail, path
    if not cur.strip():
        title = os.path.basename(os.path.abspath(evd))
        return "# {} — evidence\n\n{}\n".format(title, block.rstrip("\n")), path
    lines = cur.splitlines()
    at = 1 if lines and lines[0].startswith("#") else 0
    return "\n".join(lines[:at] + ["", block.rstrip("\n"), ""] + lines[at:]) + "\n", path


def write(evd):
    new, path = apply(evd)
    if read(path) == new:
        return False, path
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(new)
    return True, path


def stale(evd):
    """The reason the gate can trust the index: '' when current, else why not."""
    cur = read(os.path.join(evd, "manifest.md"))
    if BEGIN not in cur or END not in cur:
        return "manifest.md carries no index block"
    want = render(evd).strip()
    have = (BEGIN + cur.split(BEGIN, 1)[1].split(END, 1)[0] + END).strip()
    return "" if have == want else "the index no longer matches the case folders"


# ---------------------------------------------------------------------------
def selftest():
    import shutil
    import tempfile
    tmp = tempfile.mkdtemp(prefix="evd-index-")
    try:
        evd = os.path.join(tmp, "SHOP-142")
        for d, man, extra in (
            ("TC_1_save10_applies_to_the_total", "RESULT: PASS\nKIND: acceptance\n", "TC1_01_cart.png"),
            ("TC_2_an_expired_code_is_refused", "RESULT: FAIL\nKIND: boundary\n", "TC2_01_error.png"),
            ("TC_10_the_orders_screen_is_intact", "RESULT: BLOCKED\nKIND: whole-screen\nREASON: no staff account\n", None),
        ):
            os.makedirs(os.path.join(evd, d))
            with open(os.path.join(evd, d, "manifest.md"), "w") as fh:
                fh.write(man)
            if extra:
                open(os.path.join(evd, d, extra), "w").close()
                open(os.path.join(evd, d, extra.replace(".png", "_boxed.png")), "w").close()

        checks = []

        def ck(cond, msg):
            checks.append(cond)
            if not cond:
                print("  x {}".format(msg))

        body = render(evd)
        ck("save10 applies to the total" in body, "the folder name is not used as the case title")
        ck("3 cases · 1 PASS · 1 FAIL · 1 BLOCKED" in body, "the tally is wrong: {!r}".format(body.splitlines()[-2]))
        ck("no staff account" in body, "a BLOCKED case must carry its reason into the index")
        ck(body.index("TC_2") < body.index("TC_10"), "TC_10 sorted before TC_2 — numeric order was not used")
        ck("TC1_01_cart_boxed.png" in body, "the boxed image is not linked")

        ck(stale(evd) != "", "a manifest with no index block must be reported stale")
        changed, path = write(evd)
        ck(changed and os.path.exists(path), "the first write did not create manifest.md")
        ck(read(path).startswith("# SHOP-142 — evidence"), "a created manifest has no title")
        ck(stale(evd) == "", "the index is stale immediately after being written")
        ck(write(evd)[0] is False, "rendering is not deterministic — a second write changed the file")

        # Prose around the block survives; a new case makes it stale again.
        with open(path, "a") as fh:
            fh.write("\n## TRACKER ATTACHMENTS\n- SHOP-142_TC1.png\n")
        os.makedirs(os.path.join(evd, "TC_3_totals_survive_a_reload"))
        with open(os.path.join(evd, "TC_3_totals_survive_a_reload", "manifest.md"), "w") as fh:
            fh.write("RESULT: PASS\nKIND: acceptance\n")
        ck(stale(evd) != "", "a new case folder did not make the index stale")
        write(evd)
        ck("TRACKER ATTACHMENTS" in read(path), "regenerating the block destroyed the prose around it")
        ck("totals survive a reload" in read(path), "the new case never reached the index")
        ck(stale(evd) == "", "still stale after a rewrite")

        # A pipe in a value must not blow a column out of the table.
        with open(os.path.join(evd, "TC_3_totals_survive_a_reload", "manifest.md"), "w") as fh:
            fh.write("RESULT: PASS\nKIND: acceptance\nTITLE: total | subtotal both update\n")
        row = [l for l in render(evd).splitlines() if "TC_3" in l][0]
        cells = len(re.findall(r"(?<!\\)\|", row))
        ck(cells == 6, "a pipe inside a value split the row into {} cells: {!r}".format(cells, row))

        failed = checks.count(False)
        print("EVD-INDEX SELFTEST: {}  ({} checks)".format("PASS" if not failed else "FAIL", len(checks)))
        return 1 if failed else 0
    finally:
        shutil.rmtree(tmp, ignore_errors=True)


def main():
    ap = argparse.ArgumentParser(description="write the case index into evd/<TICKET>/manifest.md")
    ap.add_argument("--evd", help="the evidence folder, e.g. evd/SHOP-142")
    ap.add_argument("--check", action="store_true", help="report staleness, write nothing")
    ap.add_argument("--selftest", action="store_true")
    a = ap.parse_args()
    if a.selftest:
        return selftest()
    if not a.evd:
        ap.print_help()
        return 2
    if not os.path.isdir(a.evd):
        print("EVD-INDEX: no such evidence folder: {}".format(a.evd))
        return 2
    if a.check:
        why = stale(a.evd)
        print("EVD-INDEX: STALE — {}\n  unblock: python3 .vteam/scripts/evd_index.py --evd {}".format(why, a.evd)
              if why else "EVD-INDEX: CURRENT  ({})".format(a.evd))
        return 1 if why else 0
    changed, path = write(a.evd)
    print("EVD-INDEX: {}  {}".format("WROTE " if changed else "UNCHANGED", path))
    return 0


if __name__ == "__main__":
    sys.exit(main())
